table _Measures_Folder
	lineageTag: f3f51354-8aa3-4ff2-a326-46c0579e67c0

	measure 'Gross MW Output HH' = ```
			Sum('Forecast'[GROSS_MW_OUTPUT_EFFECTIVE])
			
			```
		formatString: #,0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 52fedb99-293c-4d59-9ce7-d2f42d07769e

	measure 'Gross MW Output Forecast' = DIVIDE( [Gross MW Output Forecast HH] ,2)
		formatString: #,0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 481d2516-acc0-4d80-bf26-376c447327db

	measure 'Gross MW Output Delta' = [Gross MW Output Forecast Today] - [Gross MW Output Today HH]
		formatString: #,0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: df3aa3b6-c284-45fd-990a-ff6e48052338

	measure 'Gross MW Output Delta %' =
			
			
			VAR _gross_actual = [Gross MW Output Today HH]
			RETURN
			if( ISBLANK(_gross_actual), "", 1- DIVIDE( [Gross MW Output Today HH],[Gross MW Output Forecast Today HH]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 19d609bc-a202-4aa0-b236-ed81595e1696

	measure 'Last Forecast Processed' = CALCULATE( max('Forecast'[CURRENT_TIME]),REMOVEFILTERS())
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _Import\Calendar
		lineageTag: 1a4cfa4d-3692-42c4-8561-a74f2a055200

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Net Output' = sum('Forecast'[NET_OUTPUT_ACTUAL])
		formatString: #,0
		displayFolder: _Import\Forecast\Net Output\Actual
		lineageTag: 5ffe4fbe-8c82-4a3f-b8cc-8cf31c4c98b8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Net Output Forecast' = sum('Forecast'[Forecast_net_output])
		formatString: #,0
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: fb5294c7-3b20-4604-befc-d1873d907cae

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Net Output Delta' = [Net Output Forecast] - [Net Output]
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output
		lineageTag: b59c388f-a4e6-4ccb-9ff2-8359f6445653

	measure 'Net Output Delta %' = ```
			1- DIVIDE( [Net Output],[Net Output Forecast]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast\Net Output
		lineageTag: a4c10052-430f-4873-b239-577faf13b35e

	measure 'Gross MW Output Today HH' = ```
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Gross MW Output HH],'Forecast'[7_DAYS_DATE] <= _result)
			
			
			```
		formatString: #,0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 7c6ba2fb-66a8-4ffe-a175-e0077d19972e

	measure 'Gross Output Completed Days Flag' = if(ISBLANK([Gross MW Output Today HH]),0,1)
		formatString: 0
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 282f819e-f8ff-492b-bb72-afff2f1d3665

	measure 'Gross MW Output Forecast Today' = ```
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Gross MW Output Forecast],'Forecast'[7_DAYS_DATE] <= _result)
			
			```
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 40aacb9e-bb35-4c51-beb0-8202c6c0ca56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross MW Output Delta All' = [Gross MW Output Forecast] - [Gross MW Output Today]
		formatString: #,0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: f52e5c36-6711-4641-923c-aa6e8dc9011b

	measure 'Ambient Temp.' = AVERAGE('Forecast'[AMBIENT_TEMP_EFFECTIVE])
		displayFolder: _Import\Temperature
		lineageTag: 56771454-b73b-451f-9428-8a2db9d86ebc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross GWh Output Today' = DIVIDE( [Gross MW Output Today],1000)
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 3ece6e24-0613-47d6-952c-d94977787eee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross GWh Output Forecast' = DIVIDE([Gross MW Output Forecast],1000)
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 4396a967-a786-4521-88d5-816ceeea6c89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross GWh Output Delta' = [Gross GWh Output Forecast] - [Gross GWh Output Today]
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 107e8fb8-c539-44b2-bfc5-c37bb368f7cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross GWh Output Delta %' =
			
			VAR _gross_actual = [Gross GWh Output Today]
			RETURN
			    if( ISBLANK(_gross_actual), "", 1- DIVIDE( [Gross GWh Output Today],[Gross GWh Output Forecast Today]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 8c6fd4e7-17a5-47ea-883d-fe1b6d8efaba

	measure 'Gross GWh Output Forecast Today' = DIVIDE([Gross MW Output Forecast Today],1000)
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: af6add2c-9939-4fa2-872e-cd49eda502eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross MW Output Forecast HH' = SUM('Forecast'[Forecast_gross_output])
		formatString: 0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: e50b61bc-8359-4aa9-aa98-3cb599f31c96

	measure 'Gross MW Output' = DIVIDE( [Gross MW Output HH],2)
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: dd237eac-e17a-4554-8e95-628f17cc7a0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross MW Output Today' = ```
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Gross MW Output],'Forecast'[7_DAYS_DATE] <= _result)
			
			```
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 9f9ad9ad-abfd-43c2-8c7e-edfee1618523

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross MW Output Forecast Today HH' =
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Gross MW Output Forecast HH],'Forecast'[7_DAYS_DATE] <= _result)
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 5b88e032-6e92-4569-bf0e-63c45354d0b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross GWh Output Delta All' = [Gross GWh Output Forecast] - [Gross GWh Output Today]
		formatString: 0.00
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 903f4366-6389-4501-ac3c-7d60a1a28d77

	measure 'Custom Calendar Selected' = IF(SELECTEDVALUE( 'Date Periods'[Type]) ="Custom",1,0)
		formatString: 0
		displayFolder: _Import\Calendar
		lineageTag: 21afeb05-2b4b-4159-bbdc-86364e12ea54

	measure 'Custom Calendar Selected Label' = IF(SELECTEDVALUE( 'Date Periods'[Type]) ="Custom","Choose a custom date","Custom date disabled")
		displayFolder: _Import\Calendar
		lineageTag: bbba6b3e-9ca2-4e26-8471-6ce782a69f43

	measure 'Date Period Selected Forecast' =
			
			--var _ini = FORMAT( DATEVALUE( CALCULATE( min('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]))), "dd/mm/yy")
			var _ini = FORMAT( DATEVALUE( MIN('Forecast'[7_DAYS_DATE])), "dd/mm/yy")
			var _end = FORMAT(DATEVALUE( CALCULATE( max('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]),'Date Periods'[Date],'Date Table'[calendar_date])), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: 5699bfaf-6405-414b-89b2-3aacf28bd5da

	measure 'Custom Calendar First Date' = MIN('Date Periods'[Date])
		formatString: General Date
		displayFolder: _Import\Calendar
		lineageTag: c1311c71-ef46-4fa4-9192-53bbb239b7c1

	measure 'Net MW Output HH' = Sum('Forecast'[NET_OUTPUT_EFFECTIVE])
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 6b6e029f-d33d-40c2-8070-acad3a183053

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output Forecast' = DIVIDE( [Net MW Output Forecast HH] ,2)
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: b62f0b93-6c0f-4178-bff4-a20ea81da3da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output Delta' = [Net MW Output Forecast Today] - [Net MW Output Today HH]
		displayFolder: _Import\Forecast\Net Output
		lineageTag: f20c6a82-fd8c-44be-b8d5-d6ff2b70d5ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output Delta %' =
			
			
			VAR _Net_actual = [Net MW Output Today HH]
			RETURN
			if( ISBLANK(_Net_actual), "", 1- DIVIDE( [Net MW Output Today HH],[Net MW Output Forecast Today HH]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast\Net Output
		lineageTag: c075ea68-9332-4521-8787-3bbe3b62ccd9

	measure 'Net MW Output Today HH' =
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Net MW Output HH],'Forecast'[7_DAYS_DATE] <= _result)
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output
		lineageTag: ec0bdeee-2ee6-400f-81f7-ed928284b5c4

	measure 'Net Output Completed Days Flag' = if(ISBLANK([Net MW Output Today HH]),0,1)
		formatString: 0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 7a4a4817-4749-46fc-8879-ab3158b09ffe

	measure 'Net MW Output Forecast Today' =
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Net MW Output Forecast],'Forecast'[7_DAYS_DATE] <= _result)
		formatString: 0
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: df473c41-0309-434d-9005-2ed67b0027ec

	measure 'Net MW Output Delta All' = [Net MW Output Forecast] - [Net MW Output Today]
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 60a85686-f2af-4f2c-83eb-ea7973a773a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net GWh Output Today' = DIVIDE( [Net MW Output Today],1000)
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: 917a9428-37d3-4756-b71e-b75017d2c6c7

	measure 'Net GWh Output Forecast' = DIVIDE([Net MW Output Forecast],1000)
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: 9a7dc5d2-e61a-4f61-afe5-56779c04796b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net GWh Output Delta' = [Net GWh Output Forecast Today] - [Net GWh Output Today]
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: 371eea4f-ea9c-4ef6-b7f0-c9c28ad70a16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net GWh Output Forecast Today' = DIVIDE([Net MW Output Forecast Today],1000)
		formatString: 0.0
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: 14247d0f-20db-4359-8d81-6baab0871c5d

	measure 'Net MW Output Forecast HH' = SUM('Forecast'[Forecast_Net_output])
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: 4cae9ebc-dd53-4ad9-9287-14b2b664dddd

	measure 'Net MW Output' = DIVIDE( [Net MW Output HH],2)
		displayFolder: _Import\Forecast\Net Output
		lineageTag: d7c448d3-ca19-48aa-bad7-9e2f1d74f5f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output Today' =
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Net MW Output],'Forecast'[7_DAYS_DATE] <= _result)
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 9f9061a9-1d08-42f0-8756-05e49726de5a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output Forecast Today HH' =
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Net MW Output Forecast HH],'Forecast'[7_DAYS_DATE] <= _result)
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: 5edfd0b6-3811-41e9-b59e-90aff4cfd8cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net GWh Output Delta All' = [Net GWh Output Forecast] - [Net GWh Output Today]
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: c6290098-dcbf-4e00-8b02-d0677aad0a95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net GWh Output Delta %' =
			
			
			VAR _net_actual = [Net GWh Output Today]
			RETURN
			if( ISBLANK(_net_actual), "", 1- DIVIDE( [Net GWh Output Today],[Net GWh Output Forecast Today]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: 18b5e631-14aa-4cae-a135-b504f2da349b

	measure 'Net GWh Output Delta Today' = [Net GWh Output Forecast Today] - [Net GWh Output Today]
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: eb90b1d9-28c3-4361-9f8d-6b4dc60768ca

	measure 'Net GWh Output Forecast Future' = CALCULATE(DIVIDE([Net MW Output Forecast],1000),  KEEPFILTERS('Date Table'[Actual Only] = "Forecast"))
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: 09cb4cdc-1061-4cbd-a0c4-0b5b3a6e4c03

	measure 'Gross GWh Output Delta Today' = [Gross GWh Output Forecast Today] - [Gross GWh Output Today]
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: f017d518-1320-44a8-841d-281622f6d1e4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output HH Avg' = AVERAGE('Forecast'[NET_OUTPUT_EFFECTIVE])
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 797f5cb8-d6de-4bbd-a01b-9c5b2d05f076

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output Forecast HH Avg' = AVERAGE('Forecast'[Forecast_Net_output])
		formatString: 0.0
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: 4d6e456e-24ba-4b4e-9b88-f7edb5773f69

	measure 'Net MW Output HH Avg Today' = CALCULATE([Net MW Output HH Avg],'Date Table'[Actual Only] = "Actual")
		formatString: 0.0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 09c0576e-4e92-4dd3-8255-cd120ff70865

	measure 'Net MW Output Delta Avg %' =
			
			
			VAR _Net_actual = [Net MW Output HH Avg Today]
			RETURN
			if( ISBLANK(_Net_actual), BLANK() , 1- DIVIDE( [Net MW Output HH Avg Today],[Net MW Output Forecast HH Avg] ))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Import\Forecast\Net Output
		lineageTag: ac46a154-9e76-4e7b-82b0-5276b38aca46

	measure 'Net MW Output HH Min' = Min('Forecast'[NET_OUTPUT_EFFECTIVE])
		formatString: 0.0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 3828875f-214a-432b-9edf-de9e02d4329d

	measure 'Net MW Output HH Max' = ```
			
			 
			 var _return = MAX('Forecast'[NET_OUTPUT_EFFECTIVE])
			
			 RETURN
			 CALCULATE(_return,KEEPFILTERS('Date Table'[calendar_date]))
			```
		formatString: 0.0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: ebef37f3-1511-47e3-af88-eed5c8704e14

	measure 'Calendar Min Latest Week' = ```
			
			
			--var _current_week = WEEKNUM([Last Refresh],21)
			--var _isSunday = if(WEEKDAY([Last Refresh]) = 1, 1,0)
			--var _min_current_week = CALCULATE( MIN('Date Table Ref'[calendar_date]),  FILTER( 'Date Table Ref','Date Table Ref'[Week Number] = _current_week+_isSunday), FILTER( 'Date Table Ref', 'Date Table Ref'[financial_year] =YEAR([Last Refresh]) ))
			
			var _current_week = WEEKNUM([Last Forecast Processed],21)
			var _isSunday = if(WEEKDAY([Last Forecast Processed]) = 1, 1,0)
			var _min_current_week = CALCULATE( MIN('Date Table Ref'[calendar_date]),  FILTER( 'Date Table Ref','Date Table Ref'[Week Number] = _current_week+_isSunday), FILTER( 'Date Table Ref', 'Date Table Ref'[financial_year] =YEAR([Last Refresh])+1 ))
			RETURN
			_min_current_week
			
			```
		formatString: General Date
		displayFolder: _Import\Calendar
		lineageTag: ef1ac849-0d32-4f93-8849-45506cb49ed7

	measure 'Calendar Min Latest 2 Weeks' = ```
			
			
			var _current_week = WEEKNUM([Last Forecast Processed],21)-1
			var _previous_week = if(_current_week = 1,52,_current_week -1)
			var _isSunday = if(WEEKDAY([Last Forecast Processed]) = 1, 1,0)
			--var _min_previous_current_week = CALCULATE( MIN( 'Date Table Ref'[calendar_date]), 'Date Table Ref'[Week Number] = _previous_week --+_isSunday,REMOVEFILTERS())
			
			 var _min_previous_current_week =CALCULATE( MIN('Date Table Ref'[calendar_date]),  FILTER( 'Date Table Ref','Date Table Ref'[Week Number] = _current_week+_isSunday), FILTER( 'Date Table Ref', 'Date Table Ref'[financial_year] =YEAR([Last Refresh])+1 ))
			
			RETURN
			_min_previous_current_week
			
			
			```
		formatString: General Date
		displayFolder: _Import\Calendar
		lineageTag: 5af3fb06-3a60-466f-bae8-4e5bee62d3d7

	measure 'Net MW Output Avg Previous Week' = ```
			
			var _weeknum = WEEKNUM(CALCULATE( min('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date])),21)
			var _previous_week = IF(_weeknum = 1,52,_weeknum -1)
			var _min_previous_current_week = CALCULATE( MIN( 'Date Table Ref'[calendar_date]), 'Date Table Ref'[Week Number] = _previous_week,REMOVEFILTERS())
			var _max_previous_current_week = CALCULATE( MAX( 'Date Table'[calendar_date]), 'Date Table'[Week Number] = _previous_week,REMOVEFILTERS())
			
			var _return = CALCULATE([Net MW Output HH Avg], 'Date Table'[calendar_date] >= _min_previous_current_week  && 'Date Table'[calendar_date] <=_max_previous_current_week, REMOVEFILTERS())
			RETURN
			_return
			
			```
		formatString: 0.0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 26e81a86-e05e-4d0b-8d28-5ab127a4f2f5

	measure 'Calendar Min Last Week' =
			
			
			var _current_week = WEEKNUM([Last Forecast Processed],21)-1
			var _isSunday = if(WEEKDAY([Last Forecast Processed]) = 1, 1,0)
			--var _min_current_week = CALCULATE( MIN('Date Table Ref'[calendar_date]), 'Date Table Ref'[Week Number] = _current_week+_isSunday)
			
			 var _min_current_week = CALCULATE( MIN('Date Table Ref'[calendar_date]),  FILTER( 'Date Table Ref','Date Table Ref'[Week Number] = _current_week+_isSunday), FILTER( 'Date Table Ref', 'Date Table Ref'[financial_year] =YEAR([Last Refresh])+1 ))
			
			RETURN
			_min_current_week
		formatString: General Date
		displayFolder: _Import\Calendar
		lineageTag: c3a69f25-8180-43f2-ba70-ec8f2e62e48b

	measure 'Ambient Temp. None' = BLANK()
		formatString: 0
		displayFolder: _Import\Temperature
		lineageTag: 6a7039be-9304-4fa0-b8f9-a5feae768488

	measure 'Net GWh Output Today Min' = ```
			
			VAR _topOne = 
			    TOPN(1,
			    SUMMARIZECOLUMNS(                     
			                'Date Table'[calendar_date],
			                "Max Net",[Net GWh Output Today]
			            ),
			            [Net GWh Output Today], ASC
			        )
			RETURN 
			 MINX(_topOne,[Max Net])
			```
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: 22ea8405-f535-4e05-a429-4ca10ae346a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net GWh Output Today Max' = ```
			
			VAR _topOne = 
			    TOPN(1,
			    SUMMARIZECOLUMNS(                     
			                'Date Table'[calendar_date],
			                "Max Net",[Net GWh Output Today]
			            ),
			            [Net GWh Output Today], DESC
			        )
			RETURN 
			 MAXX(_topOne,[Max Net])
			```
		displayFolder: _Import\Forecast\Net Output\GWh
		lineageTag: ea896f09-2228-4873-91cf-ee86c8779583

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross  GWh Output Forecast Future' = CALCULATE(DIVIDE([Gross MW Output Forecast],1000),  KEEPFILTERS('Date Table'[Actual Only] = "Forecast"))
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: f23d9de1-021d-4126-8348-8b66db4a11fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output HH Min Treated' = CALCULATE( [Net MW Output HH Min], 'Forecast'[Steam Release] =0)
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 8156f791-51f5-4144-ab17-6ac29d0b9570

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Output Max Limit' = 107.8
		displayFolder: _DQ\Limits
		lineageTag: b5cbe4f7-420b-470b-a6ed-5520edf7502e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Station Enthalpy Actual Avg' = AVERAGE('Forecast'[STATION_ENTHALPY_EFFECTIVE])
		formatString: #,0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: f0355643-f93c-4c30-8548-58ed65dec91c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Slugging Limit - Fletcher Ave 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[slugging_limit_fletcher_ave])
		formatString: #,0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 971f4c6a-6d79-4196-af49-305806326077

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Slugging Limit - Putauaki 1h Bin Last 24h' = AVERAGE('DQ 30 Min Bin Last 12h'[slugging_limit_putauaki])
		formatString: #,0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 022b914f-8997-4f1b-bf04-1443d17d4653

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Slugging Limit - CHH  30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[slugging_limit_chh])
		formatString: #,0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 1618cbee-59f9-4ca2-a2b4-8dc6fedc6f74

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Last Refresh' = max('DQ Last Refresh'[system_date])
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _DQ\Refresh Dates
		lineageTag: e435aa88-1859-4924-9410-a4376248f6b3

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ Net Output Avg Last 24h' = AVERAGE('DQ 2 Min Avg Last 24h'[KAWERAU_TOTAL_MW])
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 24 h Avg
		lineageTag: 8a5ebf89-e343-45b8-8e4e-31851f5cce35

	measure 'DQ Next Refresh' = [DQ Last Refresh] + TIME(00,5,00)
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _DQ\Refresh Dates
		lineageTag: 0541b1db-1cb5-415b-b758-ecaa987d40d7

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ Net Output 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[KAWERAU_TOTAL_MW])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: e4a147ce-8417-4ba7-ba86-76d85d6bcefc

	measure 'DQ Ambient Temp. 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[AMBIENT_TEMP])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 444b195e-c79f-464a-bbdf-654235d44df4

	measure 'DQ Station Enthalpy 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[STATION_ENTHALPY])
		formatString: #,0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 8b011489-1cd4-4730-ac93-d6a62fdf74f1

	measure 'Total Steam Flow Max Limit' = 786
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: 37abbbeb-b638-4af9-a58b-bd42f87ea4b9

	measure 'Net Output Min Limit' = 90
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: b7169ba7-a35f-4037-b8cf-c438c1887143

	measure 'Slugging Limit - CHH Max Limit' = 2000
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: e57a3c75-ae74-44d0-9664-25e967237fbc

	measure 'Slugging Limit - Fletcher Max Limit' = 1150
		formatString: #,0
		displayFolder: _DQ\Limits
		lineageTag: 83a43ad2-ff36-4f5e-8307-5cb0e402f707

	measure 'Slugging Limit - Putauaki Max Limit' = 910
		formatString: #,0
		displayFolder: _DQ\Limits
		lineageTag: edf48c5c-baaa-4078-9a0e-8dd2dfa04563

	measure 'DQ Net Forecast Last HH Value & Date Time' =
			
			
			var _minHour =  HOUR( max('DQ 2 Min Bin Last 50Min'[Time] ))
			var _minMinu =  MINUTE( max('DQ 2 Min Bin Last 50Min'[Time]))
			VAR _mindate = DATEVALUE( max('DQ 2 Min Bin Last 50Min'[Date]))
			var _minuRound = IF(_minMinu >= 30, TIME(_minHour, 30,0),TIME(_minHour,0,0))
			var _netForecast = CALCULATE(max('Forecast'[Forecast_net_output]), FILTER( 'Date Table','Date Table'[calendar_date] = _mindate),FILTER('Time Table', 'Time Table'[Time] =_minuRound))
			RETURN
			
			FORMAT(_netForecast, "##0.0") & " MW to " &FORMAT(_mindate,"dd/mm/yy") & " at " & FORMAT(_minuRound, "HH:mm")
		displayFolder: _DQ\Forecast x Streaming
		lineageTag: 1cc85dc6-962a-4ea6-8b7d-912c11a83814

	measure 'DQ Total Steam Flow 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[TOTAL_TURBINE_STEAM_FLOW])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 1a8f1b69-2b55-47f9-993d-16658f4ecba7

	measure 'Slugging Limit - CHH - Min Limit' = 1600
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: 2f3e3d37-97b6-4a51-8b25-128bdd64e13d

	measure 'Slugging Limit - CHH - Max Limit' = 2050
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: 61b1a182-77f1-487e-9887-eb71e15ca614

	measure 'Total Steam Flow Min Limit' = 700
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: 40b1e384-888c-42f9-b580-5fb4e78b2b3c

	measure 'DQ Net Output Avg Last 48h' = AVERAGE('DQ 2 Min Bin Last 48h'[KAWERAU_TOTAL_MW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 48 h
		lineageTag: 56a1923c-bbb4-4629-a361-70c20647543f

	measure 'Last Refresh' = max('Last Refresh'[system_date])
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _Import\Calendar
		lineageTag: 542fc94b-6fec-4531-a8af-acaec7a0ce45

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ Steam Flow Avg Last 48h' = AVERAGE('DQ 2 Min Bin Last 48h'[TOTAL_TURBINE_STEAM_FLOW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 48 h
		lineageTag: e2839bbe-9eb8-4f50-a5e1-1d68256aee33

	measure 'Net NW Output Current Date' =
			
			VAR _lastrefresh = [Last Refresh]
			RETURN
			CALCULATE([Net MW Output Forecast HH], 'Date Table'[date_key] = VALUE( YEAR(_lastrefresh) &  FORMAT(MONTH(_lastrefresh),"00") & DAY(_lastrefresh)))
		formatString: 0.00
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 3bf16e8d-a045-453f-968e-06611b469dee

	measure 'Last Forecast Date' = CALCULATE(MAX('Forecast'[7_DAYS_DATE]),REMOVEFILTERS())
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _Import\Calendar
		lineageTag: 26d7f1ba-19fa-4034-9703-75ec53b96a41

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ Net Output Min Last 48h' = Min('DQ 2 Min Bin Last 48h'[KAWERAU_TOTAL_MW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 48 h
		lineageTag: 22fcdbca-1618-467c-9bec-f57effe27660

	measure 'DQ Net Output Max Last 48h' = Max('DQ 2 Min Bin Last 48h'[KAWERAU_TOTAL_MW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 48 h
		lineageTag: d96f98a5-9797-4d91-9518-8e1f1336fc4a

	measure 'DQ Steam Flow Min Last 48h' = min('DQ 2 Min Bin Last 48h'[TOTAL_TURBINE_STEAM_FLOW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 48 h
		lineageTag: 34e673d5-c69b-43cf-af20-4b69965b0ae5

	measure 'DQ Steam Flow Max Last 48h' = max('DQ 2 Min Bin Last 48h'[TOTAL_TURBINE_STEAM_FLOW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 48 h
		lineageTag: ba5f602c-f1ab-42bd-afa4-f62a60a643c2

	measure 'DQ Station Enthalpy Avg Last 24h' = AVERAGE('DQ 2 Min Avg Last 24h'[STATION_ENTHALPY])
		formatString: #,0
		displayFolder: _DQ\2 Min Bin Last 24 h Avg
		lineageTag: 0371fef4-c87d-4040-86b5-7c1f1f15c33b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Cooling WT 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[MAIN_COOLING_WATER_TEMPERATURE])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 23b734d4-ae5a-4427-84e9-7649c261a71f

	measure 'DQ Ambient Temp. Avg Last 24h' = AVERAGE('DQ 2 Min Avg Last 24h'[AMBIENT_TEMP])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 24 h Avg
		lineageTag: c96332a4-c36d-4ab3-bc33-4b894f00cf91

	measure 'DQ Cooling WT Avg Last 24h' = AVERAGE('DQ 2 Min Avg Last 24h'[MAIN_COOLING_WATER_TEMPERATURE])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 24 h Avg
		lineageTag: 8e847131-b063-44a0-8020-5149a1c2ba09

	measure 'DQ Enthalpy Avg Last 24h Variance Colour' =
			
			var _return = [DQ Station Enthalpy Avg Last 24h]
			RETURN
			SWITCH(
			    TRUE(),
			    _return < 1210, [Colour Red Pastel],
			    _return >= 1210 && _return <= 1218, [Colour Green Pastel],
			    _return > 1218, [Colour Orange Pastel]
			)
		displayFolder: _DQ\Variance Colour
		lineageTag: a9ec8418-8b9c-463c-9145-f5bc569e5bec

	measure 'DQ Net Output Last 2Min Variance Colour' = ```
			
			var _variance =  [DQ Net Output 2Min Bin Last 50Min Last Val] - [DQ Net Output Avg Last 24h]
			RETURN
			  if(_variance<0, [Colour Red Pastel], [Colour Green Pastel])
			
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: e67b4808-4daf-4133-9479-378447db762a

	measure 'DQ HP Steam Flow Turbine 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[HP_STEAM_FLOW_AT_TURBINE])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 43d304e9-2a3a-4de9-963a-4da81c0575e6

	measure 'DQ LP Steam Flow 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[LP_STEAM_FLOW])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 9e2829b9-4b65-4612-8a94-2983eabd2e2d

	measure 'DQ Gross Output 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[GROSS_MW_OUTPUT])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 2c257c3c-aec0-4fa0-b958-24e20cceee62

	measure 'DQ HP Brine Flow 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[HP_BRINE_FLOW])
		formatString: #,0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: c7b9c17e-5da2-4be8-a04c-00ba5a689bff

	measure 'Colour Red' =
			"red"
			--"#ff686b"
		displayFolder: Colours
		lineageTag: 85716abc-5cb8-47f2-b40f-13c3441b0373

	measure 'Colour Green' = ```
			"green"
			--"#84dcc6"
			  
			```
		displayFolder: Colours
		lineageTag: 16f92642-925f-46f1-acaa-9e99dfd7a5b9

	measure 'Colour Orange' =
			"orange"
			--"#ff9770"
		displayFolder: Colours
		lineageTag: 6192d8c4-1735-4de7-800f-cdac1e8addf3

	measure 'Colour Red Orange' =
			"#ca6702"
			 -- "#ff928b"
		displayFolder: Colours
		lineageTag: 74747719-0efe-43a2-9e9f-18ee536fa0c3

	measure 'DQ HP Brine Last 24h Variance Colour' = ```
			
			var _return = [DQ HP Brine Flow 30 Min Bin Last 12h] 
			RETURN
			SWITCH(
			    TRUE(),
			    _return > 2100, [Colour Red],
			    _return >= 1900 && _return <= 2100, [Colour Green],
			    _return < 1900, [Colour Orange]
			)
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: a96ccb2f-7ee9-4845-b56f-7b4f40312807

	measure 'DQ Station Take + NTGA 30 Min Bin Last 12h' = [DQ HP Brine Flow 30 Min Bin Last 12h] + [DQ HP Steam Flow Turbine 30 Min Bin Last 12h]
		formatString: #,0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: d82dd6cd-b437-45d1-8ec6-90e618341199

	measure 'DQ Cooling WT 30 Min Bin x Avg Last 24h' = [DQ Cooling WT 30 Min Bin Last 12h] - [DQ Cooling WT Avg Last 24h]
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: daa565c0-7d06-4479-bd34-d3e840be6073

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Ambient Temp. 30 Min Bin x Last 12h' = [DQ Ambient Temp. 30 Min Bin Last 12h] - [DQ Ambient Temp. Avg Last 24h]
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: fdce318b-1c29-46f8-b6cf-262d788b5f3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Humidity 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[HUMIDITY])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: cd9caaee-1eb4-45ab-8b3b-34b39e01d144

	measure 'DQ Humidity Avg Last 24h' = AVERAGE('DQ 2 Min Avg Last 24h'[HUMIDITY])
		displayFolder: _DQ\2 Min Bin Last 24 h Avg
		lineageTag: 42e08a37-4dd4-4649-8695-419d75055cd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Humidity 30 Min Bin x Last 12h' = [DQ Humidity 30 Min Bin Last 12h] - [DQ Humidity Avg Last 24h]
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 103f173d-ded8-4438-8621-de7970d78bb0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Station Enthalpy 30 Min Bin x Last 24h' = [DQ Station Enthalpy 30 Min Bin Last 12h] - [DQ Station Enthalpy Avg Last 24h]
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 7da1eb6c-a06f-4712-af55-90037504392a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Net Output 30 Min Bin x Last 12h' = [DQ Net Output 30 Min Bin Last 12h] - [DQ Net Output Avg Last 24h]
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 0a772ed8-8cae-420e-bed1-50411325eb91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ HP Brine Flow Avg Last 24h' = AVERAGE('DQ 2 Min Avg Last 24h'[HP_BRINE_FLOW])
		displayFolder: _DQ\2 Min Bin Last 24 h Avg
		lineageTag: d20df5c1-ea35-466a-9d9f-61d1ab33bf7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ NTGA Steam Flow 30 Min Bin Last 12h' = AVERAGE('DQ 30 Min Bin Last 12h'[NTGA_STEAM_FLOW])
		formatString: 0
		displayFolder: _DQ\30 Min Bin Last 12 h
		lineageTag: 5298790f-ad0d-40dc-9108-60748251623e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Net GWh Yesterday' = SUM('DQ GWh Yesterday Today'[net_ghwh_yesterday])
		formatString: 0.000
		displayFolder: _DQ\Net GWh
		lineageTag: 91e66613-8e28-4018-b280-1c62c25de519

	measure 'DQ Net GWh Today' = SUM('DQ GWh Yesterday Today'[net_gwh_today])
		formatString: 0.000
		displayFolder: _DQ\Net GWh
		lineageTag: 834cbfa3-7fd1-4c5a-be57-7ecf48b36513

	measure 'Station Enthalpy Max Limit' = 1240
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: ba2b313d-120e-48d7-b842-07e45accd17d

	measure 'Station Enthalpy Min Limit' = 1170
		formatString: 0
		displayFolder: _DQ\Limits
		lineageTag: 92597069-00d9-4d34-aa94-1a83f2a76b88

	measure 'Colour Red Pastel' = "#ff686b"
		displayFolder: Colours
		lineageTag: ff009b94-57be-44de-a823-c0f2921613e6

	measure 'DQ Net Output 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[KAWERAU_TOTAL_MW])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: cc5d558e-9776-48b6-8097-a6709c6f34e8

	measure 'DQ Ambient Temp. 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[AMBIENT_TEMP])
		formatString: 0.0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: e769a342-5272-4c50-a856-6a4735bbaad9

	measure 'DQ Cooling WT 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[MAIN_COOLING_WATER_TEMPERATURE])
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: dcc59912-720e-4aaf-bae5-7bb9ee1598dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ HP Steam Flow Turbine 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[HP_STEAM_FLOW_AT_TURBINE]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: c788347b-d6e2-4df6-a4cc-2c9d4354fd42

	measure 'DQ LP Steam Flow 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[LP_STEAM_FLOW]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 1908b7a6-d0c5-45b8-b80e-62a2ffd1e3e6

	measure 'DQ Total Steam Flow 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[TOTAL_TURBINE_STEAM_FLOW]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 43ccf510-45d7-4205-a6d5-f326d96a4dab

	measure 'DQ Station Take + NTGA 2Min Bin Last 50Min Last Val' = [DQ HP Brine Flow 2Min Bin Last 50Min Last Val] + [DQ HP Steam Flow Turbine 2Min Bin Last 50Min Last Val]
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 9a790c6b-d904-4045-8450-1f39701ab773

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ HP Brine Flow 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[HP_BRINE_FLOW]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: #,0.0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 949a0ea0-ef72-4da5-9ce5-42d8b3faaa78

	measure 'DQ NTGA Flow 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[NTGA_STEAM_FLOW]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: f95f1c06-a11b-4fd6-b579-520d052c3950

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Ambient Temp. 2Min Bin Last 50Min Last Val' = CALCULATE([DQ Ambient Temp. 2Min Bin Last 50Min], 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 5bb60d2f-c71f-4ba5-93de-78eb282da70d

	measure 'DQ Cooling WT 2Min Bin Last 50Min Last Val' = CALCULATE([DQ Cooling WT 2Min Bin Last 50Min], 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: ce5e6696-c16c-4f83-8512-6d3e8ee223cb

	measure 'DQ Humidity 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[HUMIDITY]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 114a6cda-4815-484a-b8a0-c9511a9847f8

	measure 'DQ Station Enthalpy 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[STATION_ENTHALPY]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: #,0.0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 09d2761b-8a1e-471c-a059-336c736b5623

	measure 'DQ Net Output 2Min Bin Last 50Min Last Val' = CALCULATE([DQ Net Output 2Min Bin Last 50Min], 'DQ 2 Min Bin Last 50Min'[ROW_NUM] =1)
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 87e7d03d-e377-4835-bcd0-4b483abd8810

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Gross Output 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[GROSS_MW_OUTPUT]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: cec629fc-6304-4535-8fd8-c6b2e4412cc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast Actual Net Output' = AVERAGE('Hindcast Model'[NET_OUTPUT_ACTUAL])
		formatString: #,0.0
		displayFolder: _Import\Hindcast
		lineageTag: 08b080ea-ba8d-434c-be8e-26fe2aa7e2a1

	measure 'Hindcast Baseline' = AVERAGE('Hindcast Model'[Net_output_baseline])
		formatString: #,0.0
		displayFolder: _Import\Hindcast
		lineageTag: 1e24e382-7d1b-4504-b44f-817d5b683586

	measure 'Hindcast 0 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_0_NTGA])    
			```
		formatString: #,0.0
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 8ee7b22b-dcdf-46c6-9cc1-3c42cf31bb69

	measure 'Date Period Selected No Forecast' =
			
			var _ini = FORMAT( DATEVALUE( CALCULATE( min('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]))), "dd/mm/yy")
			var _end = FORMAT(DATEVALUE(  MAX('Last Refresh'[system_date])), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: c270389e-4af9-47b6-bc1a-b3e9dc8ebf18

	measure 'DQ Net GWh Trending Towards' = ```
			
			var _lasthour =  HOUR(CALCULATE( MAX('DQ 30 Min Bin Last 12h'[Hour]),'DQ 30 Min Bin Last 12h'[ROW_NUM] = 1))
			RETURN  
			DIVIDE( [DQ Net GWh Today],_lasthour)*24
			```
		formatString: 0.000
		displayFolder: _DQ\Net GWh
		lineageTag: 3757d707-484f-4a83-b88c-56da7f107e0c

	measure 'DQ Net Output 2Min Latest x Last 24h' = [DQ Net Output 2Min Bin Last 50Min Last Val] - [DQ Net Output Avg Last 24h]
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: abe49565-af25-4fc2-9b51-6a8e85e6ef2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Total Steam Flow 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[TOTAL_TURBINE_STEAM_FLOW])
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 848e96a9-60ad-4bb8-aedb-c626879f073c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Station Enthalpy 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[STATION_ENTHALPY])
		formatString: #,0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 459e09cd-ec5d-42be-828e-b5e75a3f0ba8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Slugging Limit - CHH - 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[slugging_limit_chh])
		formatString: #,0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 05386719-7126-4cf1-937c-f286d35f49f4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Slugging Limit - Fletcher Ave - 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[slugging_limit_fletcher_ave])
		formatString: #,0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 5703fd7d-afde-40d5-a83e-4cb0fcf4a5b2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Slugging Limit - Putauaki - 2Min Bin Last 50Min' = AVERAGE('DQ 2 Min Bin Last 50Min'[slugging_limit_putauaki])
		formatString: #,0
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: de0788a2-6593-479d-9e01-9b8b53f3941a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ Net Output Last 2Min x 24h Variance Colour' = ```
			
			var _variance =  [DQ Net Output 2Min Bin Last 50Min Last Val] - [DQ Net Output Avg Last 24h]
			RETURN
			  if(_variance<0, [Colour Red], [Colour Green])
			
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: 9208c363-4766-4178-89a2-15a84b147e3f

	measure 'DQ Total Steam Flow Last 2Min Variance Colour' =
			
			var _return = [DQ Total Steam Flow 2Min Bin Last 50Min Last Val]
			RETURN
			SWITCH(
			    TRUE(),
			    _return > 786, [Colour Red Pastel],
			    _return > 780 && _return <= 786, [Colour Green Pastel],
			    _return < 780 , [Colour Orange Pastel]
			)
		displayFolder: _DQ\Variance Colour
		lineageTag: b4740678-5c66-4699-871e-1238c1f86a68

	measure 'DQ HP Steam Flow Turbine Last 2Min Variance Colour' =
			
			var _return = [DQ HP Steam Flow Turbine 2Min Bin Last 50Min Last Val]
			RETURN
			SWITCH(
			    TRUE(),
			    _return < 520, [Colour Red Orange],
			    _return >= 520 && _return <= 535, [Colour Orange Pastel],
			    _return > 535 && _return <= 540, [Colour Green Pastel],
			    _return > 540, [Colour Red Pastel]
			)
		displayFolder: _DQ\Variance Colour
		lineageTag: 08237ec6-6f9c-48e4-9428-bf8e80b81034

	measure 'DQ LP Steam Flow Last 2Min Variance Colour' =
			
			var _return = [DQ LP Steam Flow 2Min Bin Last 50Min Last Val]
			RETURN
			SWITCH(
			    TRUE(),
			    _return < 240, [Colour Orange Pastel],
			    _return > 240 && _return <= 266, [Colour Green Pastel],
			    _return > 266 , [Colour Red Pastel]
			)
		displayFolder: _DQ\Variance Colour
		lineageTag: d46bbaca-34a8-4cfd-bf27-9017af3ff0ef

	measure 'DQ Cooling WT Last 2Min Variance Colour' =
			
			var _variance =  [DQ Cooling WT 2Min Bin Last 50Min Last Val] - [DQ Cooling WT Avg Last 24h]
			
			RETURN
			  if(_variance<=0, [Colour Green Pastel],  [Colour Red Pastel] )
		displayFolder: _DQ\Variance Colour
		lineageTag: 44715546-3f9a-4c3e-a13b-90d6324ce506

	measure 'DQ Ambient Temp. Last 2Min Variance Colour' = ```
			
			var _variance =  [DQ Ambient Temp. 2Min Bin Last 50Min Last Val] - [DQ Ambient Temp. Avg Last 24h]
			RETURN
			
			  if(_variance<=0 && not ISBLANK(_variance), [Colour Green Pastel], if (not ISBLANK(_variance), [Colour Red Pastel],"#FFF433"))
			  
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: b480a97d-ec7d-4378-9716-15fe676b23b7

	measure 'DQ Humidity Last 2Min x 24h Variance Colour' = ```
			
			var _variance =  [DQ Humidity 2Min Bin Last 50Min Last Val] - [DQ Humidity Avg Last 24h]
			RETURN
			  if(_variance<=0, [Colour Green Pastel], [Colour Red Pastel])
			
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: 145becd7-e58e-4014-bcd5-1aed4672dff3

	measure 'DQ Net GWh Yesterday in MW' = DIVIDE([DQ Net GWh Yesterday],24)*1000
		displayFolder: _DQ\Net GWh
		lineageTag: 2991ac05-99a2-4d15-8fdc-192c64e2dde9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Net GWh Trending Towards in MW' = DIVIDE([DQ Net GWh Trending Towards],24)*1000
		displayFolder: _DQ\Net GWh
		lineageTag: ed64553f-1a8e-408f-b242-f3352979153b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Net GWh Today in MW' = ```
			
			var _lastday = MAX('DQ 30 Min Bin Last 12h'[Date])
			  var _return = CALCULATE([DQ Net Output 30 Min Bin Last 12h],'DQ 30 Min Bin Last 12h'[Date]= _lastday)
			 RETURN
			  _return  
			```
		displayFolder: _DQ\Net GWh
		lineageTag: df5de2b2-c71c-4812-bdcd-4abe4bb81f71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Yesterday MW x Today MW' = [DQ Net GWh Today in MW] - [DQ Net GWh Yesterday in MW]
		displayFolder: _DQ\Net GWh
		lineageTag: 2e9f0652-ca64-461d-9471-04f2786f6baa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Net GWh Today x Yesterday MW Variance Icon' = ```
			
			 
			 var _up_arrow = UNICHAR(129137)
			 var _down_arrow = UNICHAR(129139)
			 var _delta = [DQ Net GWh Today in MW] - [DQ Net GWh Yesterday in MW] 
			var _variance =  DIVIDE(_delta,  [DQ Net GWh Today in MW])
			
			RETURN
			    if ( 
			        _variance > 0,FORMAT(  _variance*100 , "0.0") & "%"  & _up_arrow,
			              if(_variance < 0,  FORMAT(_variance *100, "0.0") & "%" & _down_arrow)
			
			    )    
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: 80c03bad-abc4-49a2-aee2-e23aa03a4f26

	measure 'Hindcast 5 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_5_NTGA])
				
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 7b1e4a61-b00f-4aa0-b120-d6511a1fc897

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 10 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_10_NTGA])
				
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 43537e5e-8577-48e9-89c9-6c03d1b1fd65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 15 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_15_NTGA])
				
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: cf97f559-c4ee-48d9-8611-2ff379b066ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 20 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_20_NTGA])
				
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: aac89034-72e4-4ec5-bc6f-70265de48e16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 25 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_25_NTGA])
				
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 513f0ba5-6ec0-4425-bf95-0bd2dfbadbb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 30 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_30_NTGA])
				
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 8a6f6d21-7f60-467d-8948-db878b16d7b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 35 t/h NTGA Steam' = ```
			AVERAGE('Hindcast Model'[Net_output_35_NTGA])
				
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 7c317bf5-06bb-44cc-8d50-524fd6364d66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Colour Green Pastel' =
			"#80ed99"
			
			 --"#84dcc6"
		displayFolder: Colours
		lineageTag: 4786d5eb-5d44-43e8-9aa1-570ec82a2e4b

	measure 'Colour Orange Pastel' = "#ff9770"
		displayFolder: Colours
		lineageTag: 31c2ab2c-9375-4e59-b2ad-cfaa5aa3cfb7

	measure 'DQ Net Forecast Last HH Value' =
			
			
			var _minHour =  HOUR( max('DQ 2 Min Bin Last 50Min'[Time] ))
			var _minMinu =  MINUTE( max('DQ 2 Min Bin Last 50Min'[Time]))
			VAR _mindate = DATEVALUE( max('DQ 2 Min Bin Last 50Min'[Date]))
			var _minuRound = IF(_minMinu >= 30, TIME(_minHour, 30,0),TIME(_minHour,0,0))
			var _netForecast = CALCULATE(max('Forecast'[Forecast_net_output]), FILTER( 'Date Table','Date Table'[calendar_date] = _mindate),FILTER('Time Table', 'Time Table'[Time] =_minuRound))
			RETURN
			_netForecast
		displayFolder: _DQ\Forecast x Streaming
		lineageTag: 4f5e8f9b-0b15-4b09-91f9-e7fdcf5c0670

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Net Forecast Last HH Date Time' =
			
			var _minHour =  HOUR( max('DQ 2 Min Bin Last 50Min'[Time] ))
			var _minMinu =  MINUTE( max('DQ 2 Min Bin Last 50Min'[Time]))
			VAR _mindate = DATEVALUE( max('DQ 2 Min Bin Last 50Min'[Date]))
			var _minuRound = IF(_minMinu >= 30, TIME(_minHour, 30,0),TIME(_minHour,0,0))
			RETURN
			
			 "Forecast from " & FORMAT(_mindate,"dd/mm/yy") & " at " & FORMAT(_minuRound, "HH:mm")
		displayFolder: _DQ\Forecast x Streaming
		lineageTag: 7072e72c-fa47-4bb5-82b1-e31f9983d5b3

	measure 'DQ Net Graph Label Title' = ```
			"Net Output (MW)" & " - " & [DQ Net Forecast Last HH Date Time] 
			```
		displayFolder: _DQ\Labels
		lineageTag: db16862e-37d6-47ee-8057-cc304b3ca2c8

	measure 'DQ Net GWh Today x Yesterday MW Variance Icon Colour' = ```
			
			 var _delta = [DQ Net GWh Today in MW] - [DQ Net GWh Yesterday in MW] 
			 var _variance =  DIVIDE(_delta,  [DQ Net GWh Today in MW])
			
			RETURN
			    if (  _variance > 0,[Colour Green], if(_variance < 0, [Colour Red],"black")  )    
			```
		displayFolder: _DQ\Variance Colour
		lineageTag: 7ca8c0d3-3845-4041-ac3c-cf586e0e6876

	measure 'DQ Net Output Last 2Min x Forecast Variance Colour' =
			
			
			var _Net = [DQ Net Output 2Min Bin Last 50Min]
			var _NetForecast = [DQ Net Forecast Last HH Value]
			var _deltaperc = DIVIDE((_Net- _NetForecast), _NetForecast)
			
			RETURN
			   SWITCH(
			        TRUE(),
			        _deltaperc <= 0.01 || _Net > _NetForecast, "#004b23",
			        _deltaperc > 0.01, [Colour Red],
			        "black"  // Default case
			    )
		displayFolder: _DQ\Variance Colour
		lineageTag: 58d16af9-289f-4c1f-9c5c-77deb7a2e902

	measure 'DQ Net Graph Label Title 40 min' = ```
			"Net Output (MW)" & " - Last 40 Minutes - "   & [DQ Net Forecast Last HH Date Time]  
			```
		displayFolder: _DQ\Labels
		lineageTag: 672d1d32-41ec-4779-8d30-ee7f9c3bcbde

	measure 'Net Output Forecast Max' = MAX('Forecast'[Forecast_net_output])
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: ef05b964-9d19-443f-be65-4b60db17f82c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Output Forecast Min' = MIN('Forecast'[Forecast_net_output])
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: cf17b0f7-90fd-4d3d-880e-910f516ea0c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Output Forecast Daily Delta' = [Net Output Forecast Max] - [Net Output Forecast Min]
		displayFolder: _Import\Forecast\Net Output\Forecast
		lineageTag: b36c7bcc-762a-491b-ad44-b48a27313e0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net MW Output HH Delta' = ```
			[Net MW Output HH Max] - [Net MW Output HH Min Treated]  
			```
		displayFolder: _Import\Forecast\Net Output
		lineageTag: a9e026f8-9ec4-489b-8b29-8b4d2fd11eca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NTGA Flow Demand Effective Sum' = SUM('Forecast'[NTGA_STEAM_FLOW_DEMAND_EFFECTIVE] )
		formatString: #,0
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 605e1e48-c864-4773-8d04-d1bb19472d48

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'NTGA Cost' =
			SUM('Forecast'[NTGA Cost])*-1
			--var _ntga = CALCULATE([NTGA Flow Demand Effective],KEEPFILTERS('Date Table'[calendar_date]),KEEPFILTERS('Time Table'[Time]))
			--var _price = CALCULATE([KAW1101 Price ($/MWh) Sum],KEEPFILTERS('Date Table'[calendar_date]),KEEPFILTERS('Time Table'[Time]))
			--return
			--DIVIDE( (0.085*[NTGA Flow Demand Effective]*[KAW1101 Price ($/MWh) Sum]),2)
			
			
			
			--0.085*_ntga * _price /2
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 2e890b09-dae4-4fa3-a76b-e2a6a58bf171

	measure 'KAW1101 Price ($/MWh) Sum' =
			SUM ( 'Forecast'[Latest_NZEM_Price])
			 --SUM ( 'KAW1101 Node Price'[Latest_NZEM_Price])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Import\Hindcast
		lineageTag: 65f02fa9-d0dc-4b76-b24b-0248b9b20efd

	measure 'Hindcast Delta Optmized MW' = [Hindcast Baseline Sum] - [Hindcast 0 t/h NTGA Steam Sum]
		displayFolder: _Import\Hindcast
		lineageTag: 9e515666-9bf1-40c8-ba6e-bde422e304a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast Delta Optmized MWh' = DIVIDE([Hindcast Delta Optmized MW],2)
		displayFolder: _Import\Hindcast
		lineageTag: 45353293-97c1-4fd4-ad59-106f66466ccd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast Baseline Sum' = SUM('Hindcast Model'[Net_output_baseline])
		displayFolder: _Import\Hindcast
		lineageTag: 6c0a49bc-5977-45ef-bf44-65a77fd63cce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 0 t/h NTGA Steam Sum' = ```
			sum('Hindcast Model'[Net_output_0_NTGA])
			
			```
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 9b99d46f-6447-43a9-8fc3-c0f28b671ada

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KAW1101 Price ($/MWh) Avg' = AVERAGE( 'Forecast'[Latest_NZEM_Price])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: _Import\Hindcast
		lineageTag: 94c0df30-7ba9-4d46-a73d-956ef02fa4e3

	measure 'NTGA Flow Demand Effective AVG' = AVERAGE('Forecast'[NTGA_STEAM_FLOW_DEMAND_EFFECTIVE] )
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: dd433210-ffcf-4846-8784-ddd202e22afd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast MW per t/h' = DIVIDE( [Hindcast Baseline] - [Hindcast 0 t/h NTGA Steam],[NTGA Flow Demand Effective AVG])
		formatString: 0.00
		displayFolder: _Import\Hindcast
		lineageTag: 1454f324-5a0b-4a99-9821-8266fe672337

	measure 'Hindcast Model Variance Actual x Baseline' = [Net MW Output HH Avg] - [Hindcast Baseline]
		displayFolder: _Import\Hindcast
		lineageTag: 2f9ad876-fb3a-4fd0-a259-167d57103064

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast MW Hedged Price $' = 120
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Import\Hindcast
		lineageTag: 729d757f-4b4f-4d6c-b299-d5b8513a9971

	measure 'Hindcast Net Benefit KAW1101 Spot Price' = ```
			[Hindcast Revenue KAW1101 Spot Price] - [NTGA Cost]
			
			```
		formatString: 0
		displayFolder: _Import\Hindcast
		lineageTag: 2181534a-1811-460e-b480-42aef09621f1

	measure 'Hindcast Net Benefit Spot' = [Hindcast Revenue Spot MW] - ( [NTGA Cost] *-1)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Import\Hindcast
		lineageTag: 66b5b097-c2f4-4976-9d3e-3195906aaa8c

	measure 'Hindcast Revenue KAW1101 Spot Price' = [Hindcast Delta Optmized MWh] * [KAW1101 Price ($/MWh) Sum]
		formatString: #,0
		displayFolder: _Import\Hindcast
		lineageTag: 68bf3e25-1346-4e73-949a-afb8d99e9cde

	measure 'Hindcast Revenue Spot MW' = [KAW1101 Price ($/MWh) Avg] * [Hindcast Delta Optmized MWh]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Import\Hindcast
		lineageTag: b2864c91-e846-4d76-aa96-183d496aaa31

	measure 'Hindcast Actual Net x Baseline %' = ```
			
			
			 var _delta = [Hindcast Baseline] -[Hindcast Actual Net Output]
			 var _variance =  DIVIDE(_delta,   [Hindcast Baseline])
			
			RETURN
			_variance
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Hindcast
		lineageTag: 2df0acd8-a547-49c9-ab6a-871c7db0719b

	measure 'Date Period Selected Hindcast' =
			
			--var _ini = FORMAT( DATEVALUE( CALCULATE( min('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]))), "dd/mm/yy")
			var _ini = FORMAT(  MIN('Hindcast Model'[TS_DATE]), "dd/mm/yy")
			var _end = FORMAT(DATEVALUE( CALCULATE( max('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]))), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: 042592b0-c13b-49b1-8c03-19d9e2048f1f

	measure 'Last Refresh Hindcast' = CALCULATE( max('Hindcast Model'[model_update_latest]),REMOVEFILTERS())
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _Import\Calendar
		lineageTag: f3a0880a-d0f7-4191-9722-5a652078b194

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ SP_OP Exhaust Flow Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[EXHAUST_FLOW_ACTUAL]) 
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 3d0d25f4-9220-455c-8263-05580ab57c1d

	measure 'DQ SP_OP Exhaust Flow Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[exhaust_flow_optimised])
			    
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 90bc8835-813e-4e5f-b447-87138c15b967

	measure 'DQ SP_OP Gross MW Output Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[GROSS_MW_OUTPUT_ACTUAL])
			    
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: b5dfe096-243e-48c5-abf6-caea55bf2b8e

	measure 'DQ SP_OP Gross MW Output Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[gross_mw_output_optimised])
			    
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: e8b850df-2452-4c17-9f30-890b5e259c23

	measure 'DQ SP_OP HP Brine Flow Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[HP_BRINE_FLOW_ACTUAL])
			    
			```
		formatString: #,0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 4c1cefbb-4cf5-466e-8c0f-ef1746d54a59

	measure 'DQ SP_OP HP Brine Flow Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[hp_brine_flow_optimised])
			    
			```
		formatString: #,0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: e6fe327e-231f-4cd7-b72f-c28b3b773574

	measure 'DQ SP_OP HP Ges Steam Supply Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[HP_GES_STEAM_SUPPLY_ACTUAL])
			 
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: d56366d2-8879-480b-9587-ed4ad3995ab8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP HP Ges Steam Supply Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[hp_ges_steam_supply_optimised])
			    
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: d4f302c1-72e6-4f54-81d7-6614cd17b019

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP HP Steam Flow All Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[HP_STEAM_FLOW_ALL_ACTUAL])
			 
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 929976b7-2725-40b0-9c87-d2ccd346d9d1

	measure 'DQ SP_OP HP Steam Flow All Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[hp_steam_flow_all_optimised])
			    
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: cc2ee51d-eb3c-4bcf-bf8f-9d3139609823

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP HP Steam Pressure Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[HP_STEAM_PRESSURE_ACTUAL])
			    
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 5bbe4a0d-30f2-43b0-a8e7-e7e126b3b67c

	measure 'DQ SP_OP HP Steam Pressure Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[hp_steam_pressure_optimised])
			    
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 6fd5e188-a1bf-46d4-aa73-2a8698f4c1dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP LP Steam Flow Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[LP_STEAM_FLOW_ACTUAL])
			 
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 69f55554-182b-4fa8-9176-dfb851c69398

	measure 'DQ SP_OP LP Steam Flow Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[lp_steam_flow_optimised])
			    
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 6ab0f9c0-6703-4488-b26c-1d3b198ea8af

	measure 'DQ SP_OP LP Steam Pressure Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[LP_STEAM_PRESSURE_ACTUAL])
			    
			```
		formatString: 0.00
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 012829e8-c3dc-4854-a84a-e9383b9c3170

	measure 'DQ SP_OP LP Steam Pressure Optimised' = ```
			AVERAGE('DQ Set Point Optimiser'[lp_steam_pressure_optimised])
			    
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: a1da5d56-6833-445a-9492-d3e8988a63df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP Net Output Actual' = ```
			sum('DQ Set Point Optimiser'[NET_OUTPUT_ACTUAL])
			    
			```
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 27ebf4c7-a867-4df5-b765-2c8cb7b6e390

	measure 'DQ SP_OP Net Output Optimised' = sum('DQ Set Point Optimiser'[net_output_optimised])
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 6c24ae7a-264e-4612-a4ed-deb5822540f1

	measure 'DQ SP_OP Two Phase Flow Actual' = ```
			AVERAGE('DQ Set Point Optimiser'[TWO_PHASE_FLOW_ACTUAL])
			 
			```
		formatString: #,0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: a2b78c8e-347e-4cd0-9fea-45abf8b5c7ea

	measure 'DQ SP_OP HP Steam Flow Turbine Actual' = AVERAGE('DQ Set Point Optimiser'[HP_STEAM_FLOW_AT_TURBINE_ACTUAL])
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 3dedcc6c-1bf9-4199-8cbb-a0c1577fbc84

	measure 'DQ SP_OP HP Steam Flow Turbine Optimised' = AVERAGE('DQ Set Point Optimiser'[hp_steteam_flow_at_turbine_optimised])
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 432baea5-6d2a-41b6-b5ef-1ba5f47045c5

	measure 'DQ SP_OP Net MW Lost Opportunity' = [DQ SP_OP Net Output Optimised] - [DQ SP_OP Net Output Actual]
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 4e81d34c-b5ca-4983-8e92-eed0ce6ba543

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP Gross MW Delta' = [DQ SP_OP Gross MW Output Actual] - [DQ SP_OP Gross MW Output Optimised]
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: fb903c24-7173-407b-8c84-6d92ee4e1f26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP Net MWh Lost Opportunity Last 24 h' = CALCULATE([DQ SP_OP Net MWh Lost Opportunity],'DQ Set Point Optimiser'[ROW_NUM] <=49)
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 7f74fc04-0489-4232-8669-7a4fb6ec489e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP Net MWh Lost Opportunity Today' =
			
			var _lastdate = MAX('DQ Set Point Optimiser'[ts_date])
			RETURN
			CALCULATE([DQ SP_OP Net MWh Lost Opportunity], 'DQ Set Point Optimiser'[ts_date] = _lastdate)
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: c4f690dd-2080-407a-8f29-d62ee5273c41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP Net MW Lost Opportunity %' = DIVIDE([DQ SP_OP Net MW Lost Opportunity],[DQ SP_OP Net Output Optimised])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 6880cccd-a062-4f6c-9019-b43415ad2a78

	measure 'DQ SP_OP Net Output Actual Avg' = AVERAGE('DQ Set Point Optimiser'[NET_OUTPUT_ACTUAL])
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 185ebad1-9d44-4629-a81d-6dd1fdbbc152

	measure 'DQ SP_OP Net Output Optimised Avg' = AVERAGE('DQ Set Point Optimiser'[net_output_optimised])
		formatString: 0.0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: ad0a16f3-7f74-4de4-85e1-348096540b49

	measure 'DQ SP_OP Last Set Point Optim. Refresh' = MAX('DQ Set Point Optimiser'[model_update_date_time])
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 7bd89763-eeec-42d7-99eb-3ce3c7df28ee

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ SP_OP LP Steam Pressure Optimised Latest' =
			AVERAGE('DQ Set Point Optimiser Latest'[lp_steam_pressure_optimised])
			--CALCULATE([DQ SP_OP LP Steam Pressure Optimised], 'DQ Set Point Optimiser'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: f07c2cd3-c8ea-4a26-8d6e-3a3c46b2784e

	measure 'DQ SP_OP LP Steam Flow Pressure Actual Latest' =
			AVERAGE('DQ Set Point Optimiser Latest'[LP_STEAM_PRESSURE_ACTUAL])
			
			--CALCULATE([DQ SP_OP LP Steam Pressure Actual], 'DQ Set Point Optimiser'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: a0cd2731-d344-497f-b284-cd2323560496

	measure 'DQ SP_OP LP Set Point Variance Colour' = ```
			
			
			 --var _delta = [DQ SP_OP LP Steam Flow Pressure Actual Latest] -[DQ SP_OP LP Steam Pressure Optimised Latest]
			 --var _variance =  DIVIDE(_delta,   [DQ SP_OP LP Steam Flow Pressure Actual Latest])
			 var _delta = [DQ LP Steam Pressure Set Point 2Min Bin Last 50Min Last Val] -[DQ SP_OP LP Steam Pressure Optimised Latest]
			 var _variance =  DIVIDE(_delta,   [DQ LP Steam Pressure Set Point 2Min Bin Last 50Min Last Val])
			 --var _variance = 0.01
			 RETURN
			 --_variance 
			    if (  _variance > 0.05 || _variance < -0.05 ,[Colour Red Pastel], "#fff100")
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 899a5e9b-ac54-439d-b514-25902d18db11

	measure 'DQ SP_OP Net MWh Lost Opportunity' = DIVIDE( [DQ SP_OP Net Output Optimised] - [DQ SP_OP Net Output Actual],2)
		formatString: 0
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 063e7b2d-26ed-4711-8e61-056d5db4f686

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'NTGA Flow Demand Effective Sum Hourly' = DIVIDE([NTGA Flow Demand Effective Sum],2)
		formatString: #,0
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 1a7ea5ce-32c8-4ef9-9441-9fe864ae4d67

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DQ SP_OP LP Set Point Variance' = ```
			
			
			 var _delta = [DQ SP_OP LP Steam Flow Pressure Actual Latest] -[DQ SP_OP LP Steam Pressure Optimised Latest]
			 var _variance =  DIVIDE(_delta,   [DQ SP_OP LP Steam Flow Pressure Actual Latest])
			 RETURN
			    _variance
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 8c5cb734-e1ad-4b21-89fd-cd81c3cac9c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP LP Last DateTime' = CALCULATE(MAX('DQ Set Point Optimiser'[ts_date_time]), 'DQ Set Point Optimiser'[ROW_NUM] = 1)
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 2ebafffe-fbe5-4bfd-bd02-69f682fea325

	measure 'DQ SP_OP LP Steam Pressure Set Point' = AVERAGE('DQ Set Point Optimiser'[LP_STEAM_PRESSURE_SET_POINT])
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: db42c3dc-d032-4c73-91e6-a35ea501f927

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP_OP LP Steam Pressure Set Point Latest' = CALCULATE([DQ SP_OP LP Steam Pressure Set Point], 'DQ Set Point Optimiser'[ROW_NUM] = 1)
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: f23753d4-0b29-4892-8ea5-4dbd152f5e16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ LP Steam Pressure Set Point 2Min Bin Last 50Min Last Val' = CALCULATE(AVERAGE('DQ 2 Min Bin Last 50Min'[LP_STEAM_PRESSURE_SET_POINT]), 'DQ 2 Min Bin Last 50Min'[ROW_NUM] = 1)
		formatString: 0.00
		displayFolder: _DQ\2 Min Bin Last 50 Min
		lineageTag: 543ddb7e-fc67-47fc-8d2a-f6ce8598ae44

	measure 'Hindcast NTGA Steam Baseline AVG' = AVERAGE('Hindcast Model'[NTGA_STEAM_Baseline] )
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: beabf020-3b57-47ff-87ef-c92cd41ce469

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hindcast 5 t/h NTGA Steam MW/th' =
			
			
			var _delta = [Hindcast 5 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "5 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,5) ,BLANK())
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 21430800-09a2-4766-a0c5-ddb77cf51bb2

	measure 'Hindcast 10 t/h NTGA Steam MW/th' =
			
			var _delta = [Hindcast 10 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "10 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,10) ,BLANK())
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 69570c98-266d-4d28-a5bd-96f6fc41c7dc

	measure 'Hindcast 15 t/h NTGA Steam MW/th' = ```
			
			 
			var _delta = [Hindcast 15 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "15 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,15) ,BLANK())  
			```
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 70b1b98e-a15a-4353-ae68-7f77a4cb87de

	measure 'Hindcast 20 t/h NTGA Steam MW/th' = ```
			
			
			var _delta = [Hindcast 20 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "20 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,20) ,BLANK())
			
			```
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 05c20ba7-7a9b-424d-bf0e-c92184c1921f

	measure 'Hindcast 25 t/h NTGA Steam MW/th' =
			
			var _delta = [Hindcast 25 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "25 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,25) ,BLANK())
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 920bf6d7-e137-4e22-b2ff-b867c02bc791

	measure 'Hindcast 30 t/h NTGA Steam MW/th' =
			
			
			var _delta = [Hindcast 30 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "30 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,30) ,BLANK())
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 3d50120c-7448-479e-b267-07c7e6d57bd9

	measure 'Hindcast 35 t/h NTGA Steam MW/th' = ```
			
			var _delta = [Hindcast 35 t/h NTGA Steam] - [Hindcast 0 t/h NTGA Steam]
			var _isSelected = CONTAINS( ALLSELECTED('Param Hindcast NTGAs'),'Param Hindcast NTGAs'[Parameter], "35 t/h NTGA")
			
			RETURN
			if (_isSelected,DIVIDE(_delta,35) ,BLANK())
			
			```
		formatString: 0.000
		displayFolder: _Import\Hindcast\NTGA
		lineageTag: 1b32055d-804f-4106-adb8-925179773682

	measure 'DQ Net Graph Label Title 30 min' = ```
			"Net Output (MW)" & " - Last 30 Minutes - "   & [DQ Net Forecast Last HH Date Time]  
			```
		displayFolder: _DQ\Labels
		lineageTag: b8ba54e2-249e-462c-b819-c19f121ce381

	measure 'Hindcast Actual Forecast Color' = ```
			
			var _date = MAX('Date Table'[calendar_date])
			
			RETURN
			--if (_date > DATE(2025,03,06), "lightgrey", "#87B5C7")
			if (_date > DATE(2025,03,06), "Forecast", "Actual")
			
			```
		displayFolder: _Import\Hindcast
		lineageTag: f4845ca5-c482-4b52-bc7e-7718d2eda843

	measure 'Hindcast Enthalpy 0 NTGA' = AVERAGE('Hindcast Model'[Enthalpy_0_NTGA])
		formatString: #,0
		displayFolder: _Import\Hindcast
		lineageTag: 0426e0d7-0a50-4c8a-b323-0ebf6dbd2704

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'QA Hindcast Days With 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Hindcast Model', 'Hindcast Model'[TS_DATE] ),
			        "@Count", COUNTROWS ( FILTER ( 'Hindcast Model', 'Hindcast Model'[TS_DATE] = EARLIER ( 'Hindcast Model'[TS_DATE] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] = 48 ) )
			
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 289fe002-d7c0-4d02-bba7-d42894242b43

	measure 'QA Hindcast Days With < 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Hindcast Model', 'Hindcast Model'[TS_DATE] ),
			        "@Count", COUNTROWS ( FILTER ( 'Hindcast Model', 'Hindcast Model'[TS_DATE] = EARLIER ( 'Hindcast Model'[TS_DATE] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] < 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 6b732f13-4656-470f-bd2b-f72fde1f08d4

	measure 'QA Forecast Days With < 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Forecast', 'Forecast'[7_DAYS_DATE] ),
			        "@Count", COUNTROWS ( FILTER ( 'Forecast', 'Forecast'[7_DAYS_DATE] = EARLIER ( 'Forecast'[7_DAYS_DATE] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] < 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 2538a0fb-5cef-46b8-9c15-169e4b0da5d9

	measure 'QA Forecast Days With 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Forecast', 'Forecast'[7_DAYS_DATE] ),
			        "@Count", COUNTROWS ( FILTER ( 'Forecast', 'Forecast'[7_DAYS_DATE] = EARLIER ( 'Forecast'[7_DAYS_DATE] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] = 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 3816c20a-1c8b-469f-863d-dfb9b7334497

	measure 'QA Hindcast Days With > 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Hindcast Model', 'Hindcast Model'[TS_DATE] ),
			        "@Count", COUNTROWS ( FILTER ( 'Hindcast Model', 'Hindcast Model'[TS_DATE] = EARLIER ( 'Hindcast Model'[TS_DATE] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] > 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 7e89e58a-c261-4b06-926c-f35000174b46

	measure 'QA Forecast Days With > 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Forecast', 'Forecast'[7_DAYS_DATE] ),
			        "@Count", COUNTROWS ( FILTER ( 'Forecast', 'Forecast'[7_DAYS_DATE] = EARLIER ( 'Forecast'[7_DAYS_DATE] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] > 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: cba3fc74-e777-4a82-980d-c6db2cceac3e

	measure 'QA Check Last Forecast Processed Status' =
			
			
			var  _deltahours =  DATEDIFF([Last Forecast Processed],[Last Refresh],HOUR)
			
			RETURN
			IF(_deltahours > 24,[Colour Red Pastel], [Colour Green Pastel])
		displayFolder: _Import\QA
		lineageTag: fb225409-675b-4a82-b71c-cdbeaf2fb237

	measure 'QA Check Last Hindcast Processed Status' =
			
			
			var  _deltahours =  DATEDIFF([Last Refresh Hindcast],[Last Refresh],HOUR)
			
			RETURN
			IF(_deltahours > 24,[Colour Red Pastel], [Colour Green Pastel])
		displayFolder: _Import\QA
		lineageTag: 7ca62dc9-cdcc-47d9-8718-989f758ff44e

	measure 'QA Forecast # Future Days' =
			
			var _count = CALCULATE( DISTINCTCOUNT('Forecast'[7_DAYS_DATE]), FILTER( 'Forecast','Forecast'[7_DAYS_DATE] >= DATE( YEAR([Last Refresh]), MONTH([Last Refresh]),Day( [Last Refresh]))))
			
			RETURN
			if (ISBLANK(_count),0, _count)
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: bbcf7c1e-f147-4ed6-a209-9608772d1514

	measure 'QA Hindcast # Future Days' =
			
			
			var _count = CALCULATE( DISTINCTCOUNT('Hindcast Model'[TS_DATE]), FILTER( 'Hindcast Model','Hindcast Model'[TS_DATE] >= DATE( YEAR([Last Refresh]), MONTH([Last Refresh]),Day( [Last Refresh]))))
			
			RETURN
			if (ISBLANK(_count),0,_count)
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 4f9d5a62-7524-45db-a755-841f3abcf21b

	measure 'Hind GES Capacity Baseline' = ```
			AVERAGE('GES Hindcast Model'[GES_capacity_baseline])
			
			```
		displayFolder: _Import\Hindcast\GES
		lineageTag: 122909be-2fbd-41bc-ab4d-e6b67da8f5c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hind GES Net 40 60' = AVERAGE('GES Hindcast Model'[Net_output_40_60])
		displayFolder: _Import\Hindcast\GES
		lineageTag: 330a1abf-faa2-4326-95cf-d632507a69f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hind GES Net 80' = AVERAGE('GES Hindcast Model'[Net_output_80])
		displayFolder: _Import\Hindcast\GES
		lineageTag: 648fa47e-cbe7-49c9-b26e-b9ecb9837b60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hind GES Net Actual' = ```
			AVERAGE('GES Hindcast Model'[NET_OUTPUT_ACTUAL])
			
			```
		displayFolder: _Import\Hindcast\GES
		lineageTag: bb1b879b-b3a3-45ad-a985-158d896f7789

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hind GES Net Baseline' = ```
			AVERAGE('GES Hindcast Model'[Net_output_baseline])
			
			```
		displayFolder: _Import\Hindcast\GES
		lineageTag: 22dc4f92-31ba-4b3b-ba54-bfb89b13228f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hind GES Parasitic Load Actual' = ```
			AVERAGE('GES Hindcast Model'[PARASITIC_LOAD_ACTUAL])
			
			```
		formatString: 0.00
		displayFolder: _Import\Hindcast\GES
		lineageTag: 93b21bac-7ef0-4081-8e13-24af67e31831

	measure 'Hind GES Parasitic Load Calc' = ```
			AVERAGE('GES Hindcast Model'[Parasitic_load_calculated])
			
			```
		displayFolder: _Import\Hindcast\GES
		lineageTag: d3959151-79b3-4173-8875-4e26f353ad7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hind GES Parasitic Load 40 60' = ```
			AVERAGE('GES Hindcast Model'[Parastic_load_40_60])
			
			```
		formatString: 0.00
		displayFolder: _Import\Hindcast\GES
		lineageTag: 81bb8a63-f24a-4018-9bdd-db7d4f24b596

	measure 'Hind GES Parasitic Load 80' = ```
			AVERAGE('GES Hindcast Model'[Parastic_load_80])
			
			```
		formatString: 0.00
		displayFolder: _Import\Hindcast\GES
		lineageTag: 5e64e958-54e6-4698-9bc8-c5e5a1340f12

	measure 'Last Refresh GES Hindcast' = CALCULATE( max('GES Hindcast Model'[model_update_latest]),REMOVEFILTERS())
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _Import\Calendar
		lineageTag: b8ef7d9f-52d7-4a8a-ba5f-369b9c3b52e0

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Hind GES Colours' =
			
			var _value = [Hind GES Capacity Baseline]
			
			RETURN
			SWITCH(TRUE(),
			    _value = 100,"#3da5d9",
			    _value > 80 && _value < 100,"#98c1d9",
			    _value =80 ,"#80ded9",
			    _value < 80, "#aeecef"
			)
		displayFolder: _Import\Hindcast\GES
		lineageTag: 8f922c9d-caa4-4643-bddf-2a8487b9db06

	measure 'Hind GES Net 80 GWh' = DIVIDE( DIVIDE(SUM('GES Hindcast Model'[Net_output_80]),2),1000)
		formatString: #,0.00
		displayFolder: _Import\Hindcast\GES
		lineageTag: ae08a489-1b8c-444c-9915-19f0299c786f

	measure 'Hind GES Net 40 60 GWh' = DIVIDE( DIVIDE(SUM('GES Hindcast Model'[Net_output_40_60]),2),1000)
		formatString: #,0.00
		displayFolder: _Import\Hindcast\GES
		lineageTag: 146c34cb-3ebc-4650-8315-ecfae25a6abc

	measure 'Hind GES Net Actual GWh' = DIVIDE( DIVIDE(SUM('GES Hindcast Model'[NET_OUTPUT_ACTUAL]),2),1000)
		displayFolder: _Import\Hindcast\GES
		lineageTag: e15662b5-d866-4973-8394-b3ac9061d553

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QA Check Last GES Hindcast Processed Status' =
			
			
			var  _deltahours =  DATEDIFF([Last Refresh GES Hindcast],[Last Refresh],HOUR)
			
			RETURN
			IF(_deltahours > 24,[Colour Red Pastel], [Colour Green Pastel])
		displayFolder: _Import\QA
		lineageTag: 9f0a67d3-92d4-4d64-be33-c7c7600fe9e3

	measure 'QA GES Hindcast Days With > 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'GES Hindcast Model', 'GES Hindcast Model'[Date] ),
			        "@Count", COUNTROWS ( FILTER ( 'GES Hindcast Model', 'GES Hindcast Model'[Date] = EARLIER ( 'GES Hindcast Model'[Date] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] > 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 9fcaf814-7994-4594-bd8e-f492137a692f

	measure 'QA GES Hindcast Days With < 48 Records' = ```
			
			VAR DaysTable = 
			    ADDCOLUMNS (
			        SUMMARIZE ( 'GES Hindcast Model', 'GES Hindcast Model'[Date] ),
			        "@Count", COUNTROWS ( FILTER ( 'GES Hindcast Model', 'GES Hindcast Model'[Date] = EARLIER ( 'GES Hindcast Model'[Date] ) ) )
			    )
			RETURN
			    COUNTROWS ( FILTER ( DaysTable, [@Count] < 48 ) )
			```
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 64f3920d-3f52-459b-9916-10692a84efe1

	measure 'Dummy Zero' = 0
		formatString: 0
		displayFolder: Support
		lineageTag: a1fed9bc-25eb-4595-ac84-2aa60dd28e88

	measure 'Forecast Ambient Temp. Forecast' = AVERAGE('Forecast'[temperature])
		displayFolder: _Import\Forecast
		lineageTag: 70f7aa9b-8442-4706-a620-8855fb2ed2a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast Ambient Temp. Used to Forecast' = AVERAGE('Forecast'[AMBIENT_TEMP])
		displayFolder: _Import\Forecast
		lineageTag: 61dd3444-248d-43a2-98ca-9ec8cf21add8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast Humidity Forecast' = AVERAGE('Forecast'[relativehumidity])
		displayFolder: _Import\Forecast
		lineageTag: 9a56d906-143c-4bc9-9e12-352eef0b7650

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast Humidity Used to Forecast' = AVERAGE('Forecast'[HUMIDITY])
		displayFolder: _Import\Forecast
		lineageTag: a34dd52b-2ce2-4c04-8e6f-a64e8e316d78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast Dummy Delta Bar' = 0.24
		displayFolder: _Import\Forecast
		lineageTag: 7cf3bd18-760a-49eb-be0d-1d6a09236134

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actual GES System' =
			
			var _GES_val = MAX('Forecast'[IS_GES_SYSTEM_CURRENT_EFFECTIVE])
			
			RETURN
			SWITCH(TRUE(),
			    _GES_val = "80_GES", 80,
			    _GES_val = "40_60_GES", 100,
			    _GES_val ="40_60_80_GES", 180
			    )
		formatString: 0
		displayFolder: _Import\Forecast
		lineageTag: 20063634-70ed-4384-b56e-cb8b6eedc904

	measure 'Forecast BRIP Color' = ```
			
			var _time = TIME(23,30,0)
			var _1st_2nd = CALCULATE( AVERAGE( 'Forecast'[Is_BRIPSystem_1st_2nd_Stage]),'Forecast'[7_DAYS_TIME] = _time)
			var _1st =  CALCULATE(AVERAGE('Forecast'[Is_BRIPSystem_1st_Stage_Only]),'Forecast'[7_DAYS_TIME] = _time)
			var _off = CALCULATE( AVERAGE('Forecast'[Is_BRIPSystem_Reinjection_Offline]), 'Forecast'[7_DAYS_TIME] = _time)
			
			var _flag = SWITCH(TRUE(),
			          _1st_2nd = 1, "#80ded9",
			            _1st =1, "#98c1d9",
			            _off =1, "#3da5d9",
			            "#edf2f4"            
			        )
			RETURN
			    _flag
			
			/*
			var _flag = SWITCH(TRUE(),
			          _1st_2nd = 1, "#caf0f8",
			            _1st =1, "#90e0ef",
			            _off =1, "#00b4d8",
			            "#edf2f4"            
			        )
			RETURN
			    _flag*/
			
			```
		displayFolder: _Import\Forecast
		lineageTag: 9f4edae6-f47a-4cc6-ad12-5c2ce5cc2fd5

	measure 'Forecast BRIP Detail' = ```
			
			
			var _time = TIME(23,30,0)
			var _1st_2nd = CALCULATE( AVERAGE( 'Forecast'[Is_BRIPSystem_1st_2nd_Stage]),'Forecast'[7_DAYS_TIME] = _time)
			var _1st =  CALCULATE(AVERAGE('Forecast'[Is_BRIPSystem_1st_Stage_Only]),'Forecast'[7_DAYS_TIME] = _time)
			var _off = CALCULATE( AVERAGE('Forecast'[Is_BRIPSystem_Reinjection_Offline]), 'Forecast'[7_DAYS_TIME] = _time)
			
			var _flag = SWITCH(TRUE(),
			           _1st_2nd = 1, "1st 2nd",
			            _1st = 1 , "1st",
			            _off = 1 , "Off",
			            "N/A"            
			        )
			RETURN
			    _flag
			```
		displayFolder: _Import\Forecast
		lineageTag: e486ba38-bb7e-4325-8918-d7b3f7a97b35

	measure 'Forecast BRIP Color HH' = ```
			
			
			var _1st_2nd = AVERAGE( 'Forecast'[Is_BRIPSystem_1st_2nd_Stage])
			var _1st =   AVERAGE('Forecast'[Is_BRIPSystem_1st_Stage_Only])
			var _off =  AVERAGE('Forecast'[Is_BRIPSystem_Reinjection_Offline])
			
			var _flag = SWITCH(TRUE(),
			          _1st_2nd = 1, "#80ded9",
			            _1st =1, "#98c1d9",            
			            _off =1, "#3da5d9",
			            "#edf2f4"            
			        )
			RETURN
			    _flag
			
			/*
			var _flag = SWITCH(TRUE(),
			          _1st_2nd = 1, "#caf0f8",
			            _1st =1, "#90e0ef",
			            _off =1, "#00b4d8",
			            "#edf2f4"            
			        )
			RETURN
			    _flag*/
			```
		displayFolder: _Import\Forecast
		lineageTag: cd61d90a-4069-4154-bd1b-c1b6a14f2fe1

	measure 'Forecast Delta Graph Data Label' = ```
			
			var _selected = SELECTEDVALUE('Flag Temp x Humidity'[Flag])
			
			RETURN
			IF(_selected = "Temperature",[Forecast Ambient Temp. Forecast] ,[Forecast Humidity Forecast])
			
			```
		displayFolder: _Import\Forecast
		lineageTag: 98c265de-a4ff-45e1-9a69-eaf1fbf073f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Forecast Delta Graph Data Label Detail' = ```
			
			
			var _selected = SELECTEDVALUE('Flag Temp x Humidity'[Flag])
			VAR _symbol = UNICHAR(916)
			
			var _delta = (1-FORMAT(IF(_selected = "Temperature", DIVIDE( [Forecast Ambient Temp. Forecast],[Forecast Ambient Temp. Used to Forecast])  , DIVIDE([Forecast Humidity Used to Forecast],[Forecast Humidity Used to Forecast])), "##.##"))*100
			
			RETURN
			IF(_selected = "Temperature", [Forecast Ambient Temp. Used to Forecast]    ,[Forecast Humidity Used to Forecast]  )
			--  _symbol & " " & _delta & " %" 
			```
		displayFolder: _Import\Forecast
		lineageTag: f4ac444c-dedd-42c2-be44-6aed84638eb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QA GES Hindcast # Future Days' =
			
			var _count = CALCULATE( DISTINCTCOUNT('GES Hindcast Model'[Date]), FILTER( 'GES Hindcast Model','GES Hindcast Model'[Date] >= DATE( YEAR([Last Refresh]), MONTH([Last Refresh]),Day( [Last Refresh]))))
			
			RETURN
			if (ISBLANK( _count),0,_count)
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 382d2f7a-dbb4-4a1e-bfb0-3d9de54eb539

	measure 'Forecast Future MW Loss' =
			
			var _value =  AVERAGE('Forecast'[future_megawattloss])
			
			RETURN
			if (not ISBLANK(_value), "FL: ")  & FORMAT( _value, "##")
		displayFolder: _Import\Forecast
		lineageTag: d79f5d76-c40f-4d4f-b26c-9a2a2cd4d2c5

	measure 'Forecast Total Future MW Loss' = SUM('Forecast'[future_megawattloss])
		formatString: #,0
		displayFolder: _Import\Forecast
		lineageTag: 442d73b6-64a9-4515-9c33-598c06b815a5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Forecast MW Loss NEW' =
			
			
			
			var _7days_date = DATEVALUE( MAX('Forecast'[7_DAYS_DATE]))
			--var _MW_Loss = AVERAGE('Forecast'[megawattloss])
			
			var _MW_Loss = CALCULATE(AVERAGE('Forecast'[megawattloss]), FILTER('Forecast',  'Forecast'[TS_DATE] = _7days_date))
			--var _MW_Loss = CALCULATE(AVERAGE('Forecast'[megawattloss]), FILTER( 'Forecast',  'Forecast'[TS_DATE] = DATE(2025,3,31)))
			--var _test = CALCULATE(max('Forecast'[megawattloss]),'Forecast'[TS_DATE] = DATE(YEAR( _7days_date),MONTH(_7days_date),DAY(_7days_date)))
			
			
			RETURN
			--DATE(YEAR(_7days_date),MONTH(_7days_date),DAY(_7days_date))
			--_test
			_7days_date
			--_MW_Loss
			--if (not ISBLANK(_value), "AL: ")  & FORMAT( _value, "##")
		formatString: General Date
		displayFolder: Support
		lineageTag: a68cd783-8567-4ff7-838c-be67e7c2184e

	measure DQ_LP_STEAM_PRESSURE_SET_POINT = ```
			AVERAGE('DQ Transformation'[LP_STEAM_PRESSURE_SET_POINT]) 
			```
		displayFolder: _DQ\Transformation
		lineageTag: b37997bd-b14d-4461-994c-a6bc404cb2e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KGL_TO_TP_RTU_MW_NET = ```
			AVERAGE('DQ Transformation'[KGL_TO_TP_RTU_MW_NET])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 70d9d236-f383-4c5b-a560-bac1d30eb567

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_BRINE_FLOW_TO_REINJECTION = ```
			AVERAGE('DQ Transformation'[BRINE_FLOW_TO_REINJECTION])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: dec19c95-0ab2-4bad-b812-a9a6062baeb1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_BRINE_FLOW_TO_REINJECTION_PRESSURE = ```
			AVERAGE('DQ Transformation'[BRINE_FLOW_TO_REINJECTION_PRESSURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 61e75122-d5ef-4543-9612-a76f4c3fd953

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_TOTAL_BRINE_REINJECTION_FLOW = ```
			AVERAGE('DQ Transformation'[TOTAL_BRINE_REINJECTION_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 417403ed-e762-43c1-b80b-381c51dde2a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_HP_BRINE_FLOW = ```
			AVERAGE('DQ Transformation'[HP_BRINE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: bf71d682-8e03-4b7a-b70d-8a43ecc4af2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KA61_PROD_WELL_TWO_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[KA61_PROD_WELL_TWO_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: a5e0b6bd-2f82-4210-9229-fe443c44e5c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KA52_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[KA52_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 18c774b5-8374-47cd-97f6-ede1267571bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KA46_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[KA46_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 9f98293e-8ad6-462a-8a64-c2289a741fb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KA45_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[KA45_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 6fd58654-7581-443e-86c6-418f2d63578d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KA41_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[KA41_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 83326856-a533-4339-b535-c2fe9c49e739

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KA42_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[KA42_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 8d71f7be-fdeb-4d32-9150-b7da7fea4e88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_PK06_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[PK06_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: d978d1dc-caa2-4a52-9bf9-5642737099e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_PK07_PROD_WELL_2_PHASE_FLOW = ```
			AVERAGE('DQ Transformation'[PK07_PROD_WELL_2_PHASE_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 69e55fad-4e27-4749-8552-99a1d33bcae8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_NTGA_STEAM_FLOW_DEMAND = ```
			AVERAGE('DQ Transformation'[NTGA_STEAM_FLOW_DEMAND])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: d0fc86fa-014d-42de-8e03-b527bbf6ed8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_HP_STEAM_PRESSURE = ```
			AVERAGE('DQ Transformation'[HP_STEAM_PRESSURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 0b9d9e4a-bf4b-43e1-b6a3-a4cd162cc468

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_HP_STEAM_FLOW_ALL = ```
			AVERAGE('DQ Transformation'[HP_STEAM_FLOW_ALL])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: ba957bde-f6a6-4d02-9d65-0924434f48c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_LP_STEAM_PRESSURE = ```
			AVERAGE('DQ Transformation'[LP_STEAM_PRESSURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 5a92fc67-419b-4d69-941e-e451979b464d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_LP_STEAM_PRESSURE_2 = ```
			AVERAGE('DQ Transformation'[LP_STEAM_PRESSURE_2])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 1ea160e5-1f76-4776-9b2e-a8110c427aca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_LP_STEAM_FLOW = ```
			AVERAGE('DQ Transformation'[LP_STEAM_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 4e510aaf-4f5b-4da0-ad72-9e4cf4e3176a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_HP_GES_STEAM_SUPPLY = ```
			AVERAGE('DQ Transformation'[HP_GES_STEAM_SUPPLY])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 5e317594-0a00-44ba-92ca-41093d574127

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_CONDENSER_HOTWELL_TEMPERATURE = ```
			AVERAGE('DQ Transformation'[CONDENSER_HOTWELL_TEMPERATURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 8d669272-dd1c-4ac4-a3f1-b978d873e4fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_INLET_COND_TEMP = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_INLET_COND_TEMP])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 7bc2e99e-074a-4d07-b92a-a59343cc16a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOL_WATER_FLOW = ```
			AVERAGE('DQ Transformation'[COOL_WATER_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 8c973adc-4200-421c-b4dc-267705d698c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_MAIN_COOLING_WATER_TEMP = ```
			AVERAGE('DQ Transformation'[MAIN_COOLING_WATER_TEMP])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 8d1d031c-7d7c-4e23-a634-10b3dc78f95e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_TOTAL_TURBINE_STEAM_FLOW = ```
			AVERAGE('DQ Transformation'[TOTAL_TURBINE_STEAM_FLOW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 2f538c7a-94b0-4782-a1a0-8dd490291c8e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_TURBINE_HP_CHAMBER_PRESSURE = ```
			AVERAGE('DQ Transformation'[TURBINE_HP_CHAMBER_PRESSURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 699ffe29-8973-44f2-97c0-9e9f50d4878d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_TURBINE_LP_CHAMBER_PRESSURE = ```
			AVERAGE('DQ Transformation'[TURBINE_LP_CHAMBER_PRESSURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: fc5065ec-342f-49fb-a26a-cc8bf0d097ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_CONDENSOR_PRESSURE_A = ```
			AVERAGE('DQ Transformation'[CONDENSOR_PRESSURE_A])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 74209a70-402d-4608-8287-64bd54d064a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_CONDENSOR_PRESSURE_B = ```
			AVERAGE('DQ Transformation'[CONDENSOR_PRESSURE_B])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 2ac80457-8a2f-400b-bec6-a00a201380dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_CONDENSOR_PRESSURE_C = ```
			AVERAGE('DQ Transformation'[CONDENSOR_PRESSURE_C])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 49564cff-4156-4adf-9157-693f309b1b90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_CONDENSOR_PRESSURE_D = ```
			AVERAGE('DQ Transformation'[CONDENSOR_PRESSURE_D])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 96092c34-632f-4ab5-bd6a-c40d60425d6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_VACCUM_PUMP_40_CURRENT = ```
			AVERAGE('DQ Transformation'[VACCUM_PUMP_40_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: ca60cce9-fb74-4a4d-8a33-3e43d8523e58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_VACCUM_PUMP_60_CURRENT = ```
			AVERAGE('DQ Transformation'[VACCUM_PUMP_60_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 72de8418-c211-4eeb-88df-8e199804d9dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_VACCUM_PUMP_80_CURRENT = ```
			AVERAGE('DQ Transformation'[VACCUM_PUMP_80_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: d82e5e1b-0a76-417d-94fe-e85a2f2ac08a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_HP_STEAM_NCG_CONTENT = ```
			AVERAGE('DQ Transformation'[HP_STEAM_NCG_CONTENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: ae49fa66-7f2d-437e-baa9-9fbc4dce45ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_GENERATOR_COOLING_AIR_TEMP_COLD_TURB = ```
			AVERAGE('DQ Transformation'[GENERATOR_COOLING_AIR_TEMP_COLD_TURB])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 61b70e2a-b803-4b48-b28e-8e19af5c959a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_GROSS_MW_OUTPUT = ```
			AVERAGE('DQ Transformation'[GROSS_MW_OUTPUT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 9d0fdbec-ca01-43a7-9355-268b270675d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_A_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_A_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: c562b223-1229-48f6-90dd-1b26f3715251

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_B_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_B_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: d43c19b1-1d98-4123-ba80-7f3becbdf65c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_C_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_C_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 886afab4-8238-4a7f-b2e8-6623b8cda7d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_D_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_D_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 5b65fdec-6b24-4699-8da6-c452982e95b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_E_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_E_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: cc9bc37e-27d9-4cd1-ac11-510f77e3b434

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_F_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_F_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 0f1eae42-ca45-4b0d-9a54-c97bdb7d5e7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_G_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_G_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: a6ed53c9-2573-4c22-966d-1dd87a26850a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_H_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_H_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 0247db02-c791-4de5-ad53-12a2f0e2fd9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_I_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_I_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 3f655cd0-7d62-4b54-b89c-cfcbcd6843a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_COOLING_TOWER_FAN_J_CURRENT = ```
			AVERAGE('DQ Transformation'[COOLING_TOWER_FAN_J_CURRENT])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: af43e504-a1c2-4b82-9ec7-1adceea5cf6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_STG_COOLING_WATER_SUPPLY_PRESSURE = ```
			AVERAGE('DQ Transformation'[STG_COOLING_WATER_SUPPLY_PRESSURE])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 79f9be79-f497-47ee-809a-90cbf1cda5fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_AMBIENT_TEMP = ```
			AVERAGE('DQ Transformation'[AMBIENT_TEMP])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 8cb37308-cc56-444c-a719-5124b4ac17ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_HUMIDITY = ```
			AVERAGE('DQ Transformation'[HUMIDITY])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: ec1d108a-ae98-45b7-b658-ba8de57e5d66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_KAWERAU_TOTAL_MW = ```
			AVERAGE('DQ Transformation'[KAWERAU_TOTAL_MW])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 883eba48-4a17-4dca-9113-7ceab0ee0538

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_NET_POWER = ```
			AVERAGE('DQ Transformation'[NET_POWER])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: a314c863-9de8-4586-8885-516a82ac3b11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_PARASITIC_LOAD = ```
			AVERAGE('DQ Transformation'[PARASITIC_LOAD])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 0d9c6e76-3422-4b2e-8f47-0834ef6700d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_STATION_ENTHALPY = ```
			AVERAGE('DQ Transformation'[STATION_ENTHALPY])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 3a023093-9fdb-407e-a18f-8250b49d4464

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_Cooling_tower_fan_total_current = ```
			AVERAGE('DQ Transformation'[Cooling_tower_fan_total_current])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 775690be-a36b-456c-9d95-902ec48e72a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_Wbt = ```
			AVERAGE('DQ Transformation'[Wbt])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 46c0deff-1949-4281-a6bb-e81677d61ce0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_Wbt_lag_1hr = ```
			AVERAGE('DQ Transformation'[Wbt_lag_1hr])
			
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: cc22487c-614c-49dc-9037-dca535d27b44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_1ST_BRIP_A_MOTOR_SPEED = ```
			AVERAGE('DQ Transformation'[1ST_BRIP_A_MOTOR_SPEED])
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 1ef30e86-8f38-440c-ab24-43b4f86ebb0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_2ND_BRIP_A_CURRENT = ```
			AVERAGE('DQ Transformation'[2ND_BRIP_A_CURRENT])
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 6709dbbf-8f7a-49fe-935c-ed20d7524207

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_1ST_BRIP_B_MOTOR_SPEED = ```
			AVERAGE('DQ Transformation'[1ST_BRIP_B_MOTOR_SPEED])
			 
			```
		displayFolder: _DQ\Transformation
		lineageTag: 5419dd19-f431-46f4-b1df-51b56404c3dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DQ_2ND_BRIP_B_CURRENT = ```
			AVERAGE('DQ Transformation'[2ND_BRIP_B_CURRENT])
			
			```
		displayFolder: _DQ\Transformation
		lineageTag: 8dacf806-1cda-40c3-b6c0-b2c10d41f89f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Transformation Rows' = COUNT('DQ Transformation'[HALF_HOUR_INTERVAL_TIMESTAMP])
		formatString: #,0
		displayFolder: _DQ\Transformation
		lineageTag: 7287cabc-0511-45e3-a844-13457f1a1bb0

	measure 'DQ Transformation Last Timestamp' = MAX('DQ Transformation'[NZT_HALF_HOUR_INTERVAL_TIMESTAMP])
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _DQ\Transformation
		lineageTag: 04736484-c00f-41b5-ad16-44c0869c1226

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'DQ Transformation Days' = DISTINCTCOUNT('DQ Transformation'[Date])
		formatString: 0
		displayFolder: _DQ\Transformation
		lineageTag: d7dafebd-52ba-4cec-bae4-dcac3918d274

	measure 'Forecast MW Loss NEW 2' =
			AVERAGE( 'Forecast Ref MW Loss'[megawattloss])
			/*--var _MW_Loss = AVERAGE('Forecast'[megawattloss])
			
			--var _MW_Loss = CALCULATE(AVERAGE('Forecast'[megawattloss]), FILTER('Forecast',  'Forecast'[TS_DATE] =  DATE(YEAR( Min('Forecast'[7_DAYS_DATE])),MONTH(MAX--('Forecast'[7_DAYS_DATE])),DAY(MAX('Forecast'[7_DAYS_DATE])))))
			var _MW_Loss = CALCULATE(AVERAGE('Forecast'[megawattloss]), FILTER( 'Forecast',  'Forecast'[TS_DATE] = DATE(2025,3,31)))
			--var _test = CALCULATE(max('Forecast'[megawattloss]),'Forecast'[TS_DATE] = DATE(YEAR( _7days_date),MONTH(_7days_date),DAY(_7days_date)))
			
			
			RETURN
			--DATE(YEAR(_7days_date),MONTH(_7days_date),DAY(_7days_date))
			--_test
			--_7days_date
			_MW_Loss
			--if (not ISBLANK(_value), "AL: ")  & FORMAT( _value, "##")
			*/
		displayFolder: Support
		lineageTag: c17228a0-01fe-49f7-b683-53b00943c15e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ QA Check Net Output Tag Status' =
			
			
			var _Net_Latest = VALUE(CALCULATE([DQ Net Output Avg Last 48h], 'DQ 2 Min Bin Last 48h'[row_num] = 1))
			var _Net_1h_Later = VALUE(CALCULATE([DQ Net Output Avg Last 48h], 'DQ 2 Min Bin Last 48h'[row_num] = 31))
			var _Net_2h_Later =  value(  CALCULATE([DQ Net Output Avg Last 48h], 'DQ 2 Min Bin Last 48h'[row_num] = 61))
			
			RETURN
			If (_Net_Latest  = _Net_1h_Later || _Net_Latest = _Net_2h_Later, "Net Tag Feed Stalled at " & _Net_Latest  , "Net Tag Feed OK")
		displayFolder: _DQ\QA
		lineageTag: 76948810-2bb0-4063-9aef-3575e62b478a

	measure 'Forecast BRIP Detail HH' = ```
			
			
			
			var _1st_2nd =  AVERAGE( 'Forecast'[Is_BRIPSystem_1st_2nd_Stage])
			var _1st =  AVERAGE('Forecast'[Is_BRIPSystem_1st_Stage_Only])
			var _off =  AVERAGE('Forecast'[Is_BRIPSystem_Reinjection_Offline])
			
			var _flag = SWITCH(TRUE(),
			           _1st_2nd = 1, "1st 2nd",
			            _1st = 1 , "1st",
			            _off = 1 , "Off",
			            "N/A"            
			        )
			RETURN
			    _flag
			```
		displayFolder: _Import\Forecast
		lineageTag: 78d2dac0-eac3-4ad2-a1db-ad2b5fd9984c

	measure 'PI Tags Qty' = COUNT('PI TAGs'[PI TAG])
		formatString: 0
		displayFolder: Support
		lineageTag: 7a7cdcd0-be62-4c4b-9c41-031135845c54

	measure 'Hindcast HH Qty' = COUNT('Hindcast Model'[TS_TIME])
		formatString: #,0
		displayFolder: _Import\Hindcast\QA Days HH
		lineageTag: fb13c1c8-ac6c-443f-85a3-6a089960a9a3

	measure 'Hindcast Days Qty' = DISTINCTCOUNT('Hindcast Model'[TS_DATE])
		formatString: 0
		displayFolder: _Import\Hindcast\QA Days HH
		lineageTag: d84cf21b-7671-4ca5-b08d-32e6e124fb24

	measure 'Hindcast Expected HH Qty' = [Hindcast Days Qty] * 48
		formatString: #,0
		displayFolder: _Import\Hindcast
		lineageTag: 15c3cfce-eb65-4047-9f14-49b413d97417

	measure 'Hincast HH Delta' = [Hindcast Expected HH Qty] - [Hindcast HH Qty]
		formatString: 0
		displayFolder: _Import\Hindcast\QA Days HH
		lineageTag: fefdea16-9b3b-4c44-a21a-9e78b55aa5eb

	measure 'DQ Steam Free Flag' = ```
			
			var _Gross_Val = [DQ Gross Output 2Min Bin Last 50Min Last Val]
			
			RETURN 
			IF(_Gross_Val>=70 && _Gross_Val <=85, "Steam Free Test in Progress, Setpoint Model isn't running", "")
			```
		displayFolder: _DQ\Set Point Optimiser
		lineageTag: 690e6807-8893-49e0-93b8-1ca41c664d3b

	measure 'QA Check Last Forecast Processed Flag' =
			
			
			var  _deltahours =  DATEDIFF([Last Forecast Processed],[Last Refresh],HOUR)
			
			RETURN
			IF(_deltahours > 24,1, 0)
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: b8669150-6520-4ba7-b484-a29dfff909e1

	measure 'QA Check Last GES Hindcast Processed Flag' =
			
			
			var  _deltahours =  DATEDIFF([Last Refresh GES Hindcast],[Last Refresh],HOUR)
			
			RETURN
			IF(_deltahours > 24,1, 0)
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: c66b1baa-e453-4111-9f25-8f98fd8980e3

	measure 'QA Check Last Hindcast Processed Flag' =
			
			
			var  _deltahours =  DATEDIFF([Last Refresh Hindcast],[Last Refresh],HOUR)
			
			RETURN
			IF(_deltahours > 24,1,0)
		formatString: 0
		displayFolder: _Import\QA
		lineageTag: 9fd9dd33-e18e-4718-889a-33fecde3cb3d

	measure 'Dummy Blank' = BLANK()
		formatString: 0
		displayFolder: Support
		lineageTag: 576ffa40-65d4-40d1-aaa0-a019e97c384b

	measure 'Alert GES Calculated' = ```
			AVERAGE('Flow Calibration Alerts'[GES_calculated])       
			```
		formatString: 0.0
		displayFolder: _Import\Alerts
		lineageTag: 1cb00acb-17c0-4a8e-b306-ad60e101f1e0

	measure 'Alert GES Actual' = ```
			AVERAGE('Flow Calibration Alerts'[HP_GES_STEAM_SUPPLY])  
			```
		formatString: 0.0
		displayFolder: _Import\Alerts
		lineageTag: b39249aa-d598-4a21-9fb5-cea53202a16e

	measure 'Alert HP Brine Actual' = ```
			AVERAGE('Flow Calibration Alerts'[HP_BRINE_FLOW])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: 2ae8ab1e-244d-4c28-8199-efa7e2fcb609

	measure 'Alert Total Turbine Steam Flow' = ```
			AVERAGE('Flow Calibration Alerts'[TOTAL_TURBINE_STEAM_FLOW])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: 70756b94-b75c-45ca-b78a-2a6c8fc63fd8

	measure 'Alert HP Turbine Steam Flow Actual' = ```
			AVERAGE('Flow Calibration Alerts'[HP_TURBINE_STEAM_FLOW])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: 52ee562a-0753-4216-99f0-12e4314cfd61

	measure 'Alert HP Turbine Steam Flow Calculated' = ```
			AVERAGE('Flow Calibration Alerts'[HP_turbine_steam_flow_calculated])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: b69c6a77-7f98-49be-9791-2583993c1b28

	measure 'Alert LP Steam Flow Actual' = ```
			AVERAGE('Flow Calibration Alerts'[LP_STEAM_FLOW])	   
			```
		formatString: 0.00
		displayFolder: _Import\Alerts
		lineageTag: b1426400-af2d-491e-b0cd-e4f616df0684

	measure 'Alert LP Steam Flow Calculated' = AVERAGE('Flow Calibration Alerts'[LP_turbine_steam_flow_calculated])
		formatString: 0.00
		displayFolder: _Import\Alerts
		lineageTag: c63f7327-18cf-4e9e-abef-c3bf5092ba20

	measure 'Alert HP Steam Flow Actual Median' = ```
			
			 
			 MEDIANX (
			    SUMMARIZE (
			        'Flow Calibration Alerts',
			        'Date Table'[calendar_date],
			        "DailyMedian", MEDIAN ( 'Flow Calibration Alerts'[HP_TURBINE_STEAM_FLOW] )
			    ),
			    [DailyMedian]
			)
			
			```
		formatString: 0.00
		displayFolder: _Import\Alerts
		lineageTag: 4543119a-9c57-418e-bcc1-20f7ae740cf9

	measure 'Alert LP Delta %' = UNICHAR(8710) & ": " & FORMAT(DIVIDE ([Alert LP Steam Flow Actual] - [Alert LP Steam Flow Calculated] ,[Alert LP Steam Flow Actual]), "Percent")
		displayFolder: _Import\Alerts
		lineageTag: 46aab524-5531-4aca-9460-89420c0d9aaa

	measure 'Alert HP Delta %' = ```
			UNICHAR(8710) & ": " & FORMAT(DIVIDE ([Alert HP Turbine Steam Flow Actual] - [Alert HP Turbine Steam Flow Calculated] ,[Alert HP Turbine Steam Flow Actual]),"Percent")
			
			```
		displayFolder: _Import\Alerts
		lineageTag: 0d39ee7a-ac00-4628-b192-2faccccacdb5

	measure 'Alert HP Brine Delta %' = UNICHAR(8710) & ": " & FORMAT(DIVIDE ([Alert HP Brine Actual] - [Alert HP Brine Calculated] ,[Alert HP Brine Actual]),"Percent")
		displayFolder: _Import\Alerts
		lineageTag: f9ff4461-e2eb-46dc-81b7-92772d56699a

	measure 'Alert GES Delta %' = UNICHAR(8710) & ": " & FORMAT( DIVIDE ([Alert GES Actual] - [Alert GES Calculated] ,[Alert GES Actual]), "Percent")
		displayFolder: _Import\Alerts
		lineageTag: c39f9288-89c5-4605-9dfd-d41176862b6e

	measure 'QA Transformation CF' = ```
			
			
			var _select_date = max('Date Periods'[Date]) 
			var _last_date_refresh = DATEVALUE([Last Refresh])
			var _last_time_refresh = UTCNOW() + TIME(12,0,0)
			var _HHs = DIVIDE(_last_time_refresh,30)-1
			
			RETURN
			
			-- max('Date Periods'[Date]) = _select_date 
			SWITCH(TRUE(),
			     max('Date Table'[calendar_date]) = _select_date && COUNT('DQ Transformation'[Time]) < _HHs, [Colour Red Pastel],
			     max('Date Table'[calendar_date])  < _select_date && COUNT('DQ Transformation'[Time]) <> 48, [Colour Red],
			     BLANK()
			)
			
			
			
			
			```
		displayFolder: _Import\QA
		lineageTag: 19b524cd-403d-453d-9231-586df6d79821

	measure 'Last Alerts Data' = CALCULATE( max('Flow Calibration Alerts'[ts]),REMOVEFILTERS())
		formatString: d/mm/yy hh:nn:ss
		displayFolder: _Import\Calendar
		lineageTag: 16f0e6d6-2763-4716-a296-9514957e90ef

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Alert LP Steam Flow Actual Median' = ```
			
			 
			 MEDIANX (
			    SUMMARIZE (
			        'Flow Calibration Alerts',
			        'Date Table'[calendar_date],
			        "DailyMedian", MEDIAN ( 'Flow Calibration Alerts'[LP_STEAM_FLOW] )
			    ),
			    [DailyMedian]
			)
			
			```
		formatString: 0.00
		displayFolder: _Import\Alerts
		lineageTag: 92161d86-01cd-4435-b526-bebac63caaaa

	measure 'Alert HP Brine Actual Median' = ```
			
			 
			 MEDIANX (
			    SUMMARIZE (
			        'Flow Calibration Alerts',
			        'Date Table'[calendar_date],
			        "DailyMedian", MEDIAN ( 'Flow Calibration Alerts'[HP_BRINE_FLOW] )
			    ),
			    [DailyMedian]
			)
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: fa5cf3bd-b924-403c-86ba-aafe4c741f55

	measure 'Alert GES Actual Median' = ```
			
			 
			 MEDIANX (
			    SUMMARIZE (
			        'Flow Calibration Alerts',
			        'Date Table'[calendar_date],
			        "DailyMedian", MEDIAN ( 'Flow Calibration Alerts'[HP_GES_STEAM_SUPPLY] )
			    ),
			    [DailyMedian]
			)
			
			```
		formatString: #,0.0
		displayFolder: _Import\Alerts
		lineageTag: 1d07d36a-66c9-4180-b378-7c129eb985c2

	measure 'Alert GES Constant' = ```
			AVERAGE('Flow Calibration Alerts'[GES_constant])       
			```
		displayFolder: _Import\Alerts
		lineageTag: ba0b1c6c-48a8-4413-9861-586c4a71e9bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alert HP Brine Delta' = DIVIDE ([Alert HP Brine Actual] - [Alert Total Turbine Steam Flow] ,[Alert Total Turbine Steam Flow])
		displayFolder: _Import\Alerts
		lineageTag: 91578b2f-0a55-4c67-81ac-e02550dd729b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alert Total Turbine Steam Flow Calculated' = ```
			AVERAGE('Flow Calibration Alerts'[Total_turbine_steam_flow_calculated])	   
			```
		displayFolder: _Import\Alerts
		lineageTag: 52df8f66-d247-484d-9f54-7051b1e0ab78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alert HP Venturi Brine' = ```
			AVERAGE('Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_HP_BRINE])	   
			```
		formatString: #,0.0
		displayFolder: _Import\Alerts
		lineageTag: d31f1543-bf76-440e-9b04-2c906d50deec

	measure 'Alert HP Venturi Brine Calculated' = ```
			AVERAGE('Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_calculated_hp_brine])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: bcf94a7e-0a8b-4b49-9fae-020b0a281a5e

	measure 'Alert HP Brine Calculated' = AVERAGE('Flow Calibration Alerts'[HP_brine_flow_calculated])
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: 3ae7b2a6-b22b-47dd-a193-3fff2372c0d5

	measure 'Alert HP Venturi Actual Median' = ```
			
			 
			 MEDIANX (
			    SUMMARIZE (
			        'Flow Calibration Alerts',
			        'Date Table'[calendar_date],
			        "DailyMedian", MEDIAN ( 'Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_HP_BRINE] )
			    ),
			    [DailyMedian]
			)
			
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts
		lineageTag: d1228769-8ae7-4f0a-96e1-bb7ec96b779d

	measure 'Alert HP Venturi Delta %' = UNICHAR(8710) & ": " & FORMAT( DIVIDE ([Alert HP Venturi Brine] - [Alert HP Venturi Brine Calculated] ,[Alert HP Venturi Brine]), "Percent")
		displayFolder: _Import\Alerts
		lineageTag: ff51f185-4239-47db-b5a6-1e743efa177c

	measure 'Alert Total Turbine Delta %' = UNICHAR(8710) & ": " & FORMAT( DIVIDE ([Alert Total Turbine Steam Flow] - [Alert Total Turbine Steam Flow Calculated] ,[Alert Total Turbine Steam Flow]), "Percent")
		displayFolder: _Import\Alerts
		lineageTag: 9798873d-0000-4fe2-adb5-24b5afdf67e1

	measure 'Alert Total Turbine Flow Median' = ```
			
			 
			 MEDIANX (
			    SUMMARIZE (
			        'Flow Calibration Alerts',
			        'Date Table'[calendar_date],
			        "DailyMedian", MEDIAN ( 'Flow Calibration Alerts'[TOTAL_TURBINE_STEAM_FLOW] )
			    ),
			    [DailyMedian]
			)
			```
		displayFolder: _Import\Alerts
		lineageTag: 9f7bca94-ee66-40b8-80a6-d84c69717e13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alert HP Brine Actual Median Flat' = ```
			
			var _ret = CALCULATE( MEDIAN( 'Flow Calibration Alerts'[HP_BRINE_FLOW]),REMOVEFILTERS('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date])) 
			
			RETURN
			row( "aa",_ret)
			 
			```
		displayFolder: _Import\Alerts
		lineageTag: 5172bcae-c483-499b-8e92-16f0024dd0f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alert Sum of Wells' = ```
			AVERAGE('Flow Calibration Alerts'[Sum_of_wells])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: f00e2d0e-6a01-4c8b-934b-794f849664a6

	measure 'Alert HP Venturi + HP Brine' = ```
			AVERAGE('Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_HP_BRINE])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 00c5a7f1-1e3a-4fb4-ae3e-e6f3bb737a59

	measure 'Alert HP Venturi + LP Brine + LP Steam' = ```
			AVERAGE('Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_LP_BRINE_plus_LP_STEAM])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: b5cabdfc-7e14-42bf-bdae-436ea9ae4b00

	measure 'Alert Total Turbine + GES + LP Brine' = ```
			AVERAGE('Flow Calibration Alerts'[TOTAL_TURBINE_FLOW_plus_GES_plus_LP_BRINE])	   
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 90d6a5c9-6c6e-44bc-8cf0-2dd26b77e363

	measure Measure = ```
			
			
			var _param_sel1 = SELECTEDVALUE('Param 2 Phase Sel 1'[Param 2 Phase Sel 1 Fields])
			var _param_sel2 = SELECTEDVALUE('Param 2 Phase Sel 2'[Param 2 Phase Sel 2 Fields])
			var _sel1 = SWITCH(TRUE(),
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]",[Alert HP Venturi + HP Brine],
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]",[Alert HP Venturi + LP Brine + LP Steam],
			        _param_sel1 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]",[Alert Total Turbine + GES + LP Brine],
			        _param_sel1 = "'_Measures_Folder'[Alert Sum of Wells]",[Alert Sum of Wells]
			    )
			
			var _sel2 = SWITCH(TRUE(),
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]",[Alert HP Venturi + HP Brine],
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]",[Alert HP Venturi + LP Brine + LP Steam],
			        _param_sel2 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]",[Alert Total Turbine + GES + LP Brine],
			        _param_sel2 = "'_Measures_Folder'[Alert Sum of Wells]",[Alert Sum of Wells]
			    )
			
			var  _delta =  _sel1 -_sel2
			var _delta_val = FORMAT(_delta,"Fixed")
			var _delta_perc = FORMAT(DIVIDE(_delta,_sel1),"Percent")
			
			RETURN
			"Delta: " & _delta_val & " Delta Percent: " & _delta_perc
			
			```
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 49634afe-3e93-4d12-a9d2-6f55f8e35833

	measure 'Alert Cross Validation Delta %' = ```
			
			
			var _param_sel1 = SELECTEDVALUE('Param 2 Phase Sel 1'[Param 2 Phase Sel 1 Fields])
			var _param_sel2 = SELECTEDVALUE('Param 2 Phase Sel 2'[Param 2 Phase Sel 2 Fields])
			var _sel1 = SWITCH(TRUE(),
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]",[Alert HP Venturi + HP Brine],
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]",[Alert HP Venturi + LP Brine + LP Steam],
			        _param_sel1 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]",[Alert Total Turbine + GES + LP Brine],
			        _param_sel1 = "'_Measures_Folder'[Alert Sum of Wells]",[Alert Sum of Wells]
			    )
			
			var _sel2 = SWITCH(TRUE(),
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]",[Alert HP Venturi + HP Brine],
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]",[Alert HP Venturi + LP Brine + LP Steam],
			        _param_sel2 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]",[Alert Total Turbine + GES + LP Brine],
			        _param_sel2 = "'_Measures_Folder'[Alert Sum of Wells]",[Alert Sum of Wells]
			    )
			
			var  _delta =  _sel1 -_sel2
			var _delta_val = FORMAT(_delta,"Fixed")
			var _delta_perc = DIVIDE(_delta,_sel1)
			
			RETURN
			_delta_perc
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 91dc3a30-f892-421f-af8b-b04104fd35be

	measure 'Alert Cross Validation Selected Variables' = ```
			
			
			var _param_sel1 = SELECTEDVALUE('Param 2 Phase Sel 1'[Param 2 Phase Sel 1 Fields])
			var _param_sel2 = SELECTEDVALUE('Param 2 Phase Sel 2'[Param 2 Phase Sel 2 Fields])
			var _sel1 = SWITCH(TRUE(),
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]","[HP Venturi + HP Brine]",
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]","[HP Venturi + LP Brine + LP Steam]",
			        _param_sel1 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]","[Total Turbine + GES + LP Brine]",
			        _param_sel1 = "'_Measures_Folder'[Alert Sum of Wells]","[Sum of Wells]"
			    )
			
			var _sel2 = SWITCH(TRUE(),
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]","[HP Venturi + HP Brine]",
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]","[HP Venturi + LP Brine + LP Steam]",
			        _param_sel2 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]","[Total Turbine + GES + LP Brine]",
			        _param_sel2 = "'_Measures_Folder'[Alert Sum of Wells]","[Sum of Wells]"
			    )
			
			
			
			RETURN
			"% Delta: " & _sel1  & " X " &_sel2 
			```
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 4e0198c3-e42c-49dd-bd10-7bee6a9f2525

	measure 'Alert Cross Validation Sel 1' = ```
			
			
			var _param_sel1 = SELECTEDVALUE('Param 2 Phase Sel 1'[Param 2 Phase Sel 1 Fields])
			var _sel1 = SWITCH(TRUE(),
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]",[Alert HP Venturi + HP Brine],
			        _param_sel1 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]",[Alert HP Venturi + LP Brine + LP Steam],
			        _param_sel1 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]",[Alert Total Turbine + GES + LP Brine],
			        _param_sel1 = "'_Measures_Folder'[Alert Sum of Wells]",[Alert Sum of Wells]
			    )
			
			
			RETURN
			_sel1
			
			```
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 692d28b5-caa4-438d-9c89-8bc463226b7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alert Cross Validation Sel 2' =
			
			
			
			var _param_sel2 = SELECTEDVALUE('Param 2 Phase Sel 2'[Param 2 Phase Sel 2 Fields])
			
			var _sel2 = SWITCH(TRUE(),
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + HP Brine]",[Alert HP Venturi + HP Brine],
			        _param_sel2 = "'_Measures_Folder'[Alert HP Venturi + LP Brine + LP Steam]",[Alert HP Venturi + LP Brine + LP Steam],
			        _param_sel2 = "'_Measures_Folder'[Alert Total Turbine + GES + LP Brine]",[Alert Total Turbine + GES + LP Brine],
			        _param_sel2 = "'_Measures_Folder'[Alert Sum of Wells]",[Alert Sum of Wells]
			    )
			
			
			RETURN
			_sel2
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: d73c7038-ddf0-4891-9534-3144478bfa05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Date Period Selected Alerts' =
			
			var _ini = FORMAT( DATEVALUE( min('Flow Calibration Alerts'[ts_date])), "dd/mm/yy")
			var _end = FORMAT( DATEVALUE( max('Flow Calibration Alerts'[ts_date])), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: 9f14732d-973b-4ec5-bc00-f5ab25834729

	measure 'Date Period Selected Set Point' =
			
			var _ini = FORMAT( DATEVALUE( min('DQ Set Point Optimiser'[ts_date])), "dd/mm/yy")
			var _end = FORMAT( DATEVALUE( max('DQ Set Point Optimiser'[ts_date])), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: b0f644c9-6149-4dab-a1fa-3921e65e8653

	measure 'Date Period Selected Transformation' =
			
			var _ini = FORMAT( DATEVALUE( min('DQ Transformation'[Date])), "dd/mm/yy")
			var _end = FORMAT( DATEVALUE( max('DQ Transformation'[Date])), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: 72c5cfe2-bd47-4f6b-a757-73cc6b327904

	measure 'Station Enthalpy Actual Avg X Validation' = ```
			
			
			var _lastdate = MAX('Flow Calibration Alerts'[ts_date])
			var _enthalpy = CALCULATE([Station Enthalpy Actual Avg],'Date Table'[calendar_date] <=_lastdate)
			RETURN
			_enthalpy
			
			```
		formatString: #,0.00
		displayFolder: _Import\Alerts\Cross Validation
		lineageTag: 36f93506-6262-440c-b005-11d2d24a9666

	measure 'Date Period Selected GES Hindcast' =
			
			--var _ini = FORMAT( DATEVALUE( CALCULATE( min('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]))), "dd/mm/yy")
			var _ini = FORMAT(  MIN('GES Hindcast Model'[Date]), "dd/mm/yy")
			var _end = FORMAT(DATEVALUE( CALCULATE( max('Date Table'[calendar_date]), ALLSELECTED('Date Table'[calendar_date]))), "dd/mm/yy")
			return
			"Period: " &  _ini & " - " & _end
		displayFolder: _Import\Calendar
		lineageTag: 26f8a0c1-a3d8-40c5-b572-f8bb1570f389

	measure 'Alert Tooltip GES' =
			
			
			"[GES Actual] = PI Tag: LBG10CF001.DACA.PV " & UNICHAR(10) &
			"[GES Calculated] = HP_STEAM_FLOW_ALL - HP_turbine_steam_flow_calculated"
		displayFolder: _Import\Alerts
		lineageTag: 476d9163-bef0-4a25-9946-4e77cb450065

	measure 'Alert Tooltip HP Brine' = ```
			
			
			"[HP Brine Actual] = PI TAG: HHU20CF001 " & UNICHAR(10) &
			"[HP Brine Calculated] = LP_turbine_steam_flow_calculated / LP_separator_quality (1) " & UNICHAR(10) &
			"(1): LP_separator_quality = CoolProp(LP DEMISTER STEAM PRESSURE, HP_brine_enthalpy (2)) " & UNICHAR(10) &
			"(2): HP_brine_enthalpy = CoolProp(HP_STEAM_PRESSURE, quality = 100%) " 
			```
		displayFolder: _Import\Alerts
		lineageTag: 413b993d-2246-438b-be10-bd053bc08587

	measure 'Alert Tooltip HP Steam Flow' = ```
			
			
			"[HP Turbine Steam Flow Actual] = HP_STEAM_FLOW_ALL - HP_GES_STEAM_SUPPLY " & UNICHAR(10) &
			"[HP Turbine Steam Flow Calculated] = C_stodola_coef_hp  sqrt(p_in_bara  p_out_bara) " & UNICHAR(10) &
			"C_stodola_coef_hp: HP Stodola coefficient, we use the median value of last 8 months = 44.18" & UNICHAR(10) &
			"p_in_bara: transform TURBINE_HP_CHAMBER_PRESSURE to bara" & UNICHAR(10) &
			"p_out_bara: transform TURBINE_LP_CHAMBER_PRESSURE to bara" 
			```
		displayFolder: _Import\Alerts
		lineageTag: c9fc7f16-23c7-4c07-8ba0-82abc92e02e6

	measure 'Alert Tooltip LP Steam Flow' = ```
			
			
			"[LP Steam Flow Actual] = PI Tag: LBA82CF001" & UNICHAR(10) &
			"[LP Steam Flow Calculated] = Total_turbine_steam_flow_calculated - HP_turbine_steam_flow_calculated"
			
			```
		displayFolder: _Import\Alerts
		lineageTag: 97229566-c61d-4373-a5e9-bef90590648e

	measure 'Alert Tooltip Total Turbine' = ```
			
			
			"[Total Turbine Actual] = PI Tag: KAW-MAA10CF001 " & UNICHAR(10) &
			"[Total Turbine Calculated] =  C_stodola_coef_Lp  sqrt(p_in_bara  p_out_bara) " & UNICHAR(10) &
			"C_stodola_coef_lp: LP Stodola coefficient = 355.45 " & UNICHAR(10) & 
			"p_in_bara: transform TURBINE_LP_CHAMBER_PRESSURE to bara " & UNICHAR(10) &
			"p_out_bara: CONDENSOR_PRESSURE_A " 
			```
		displayFolder: _Import\Alerts
		lineageTag: 68cdcac9-077a-41a6-a972-4d0be373e680

	measure 'Alert Tooltip Two Phase' = ```
			
			
			"[HP Brine Actual] = PI TAG: HHU20CF001 " & UNICHAR(10) &
			"[HP Brine Calculated] = LP_turbine_steam_flow_calculated / LP_separator_quality (1) " & UNICHAR(10) &
			"(1): LP_separator_quality = CoolProp(LP_STEAM_PRESSURE_2, HP_brine_enthalpy (2)) " & UNICHAR(10) &
			"(2): HP_brine_enthalpy = CoolProp(HP_STEAM_PRESSURE, quality = 100%) " 
			```
		displayFolder: _Import\Alerts
		lineageTag: 6d4aa0a7-2425-4a5d-8a3b-bd4a047e462f

	measure 'Alert Tooltip Two Phase Flow' = ```
			
			"[Two Phase Actual] =  HP_STEAM_FLOW_ALL + HP_BRINE_FLOW " & UNICHAR(10) &
			"[Two Phase Calculated] = HP_STEAM_FLOW_ALL + [HP Brine Calculated]"
			
			
			```
		displayFolder: _Import\Alerts
		lineageTag: d860a7a2-c1ba-41fa-8043-52058358737c

	measure 'DQ SP OP 30 Min LP Steam Flow Optimised' = AVERAGE('DQ 30 Min Bin Last 12h'[lp_steam_flow_optimised])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: 899038f6-05b8-4c6f-b19e-4e0c54f291e4

	measure 'DQ SP OP 30 Min Exhaust Flow Optimised' = ```
			AVERAGE('DQ 30 Min Bin Last 12h'[exhaust_flow_optimised])
			
			
			```
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: c98a0376-17e4-45d1-aa39-cbd78ff39e14

	measure 'DQ SP OP 30 Min LP Steam Pressure Actual' = ```
			AVERAGE('DQ 30 Min Bin Last 12h'[LP_STEAM_PRESSURE_ACTUAL])
			
			
			```
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: 510ff04c-213c-4c4f-a441-2b98e2fbf774

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP OP 30 Min LP Steam Pressure Set Point' = ```
			AVERAGE('DQ 30 Min Bin Last 12h'[LP_STEAM_PRESSURE_SET_POINT])
			
			```
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: 2de48c08-6e2f-4a1e-b388-8805803a967e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP OP 30 Min LP Steam Pressure Optimised' = ```
			AVERAGE('DQ 30 Min Bin Last 12h'[lp_steam_pressure_optimised])
			
				   
			
			```
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: eaf7402e-eddc-4e73-8798-2c2dc355a52a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP OP 30 Min Net Output Optimised' = AVERAGE('DQ 30 Min Bin Last 12h'[net_output_optimised])
		formatString: 0.0
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: d3451b79-2c07-49cd-b80e-a21dd74cb374

	measure 'DQ SP OP 30 Min Net MW Lost Opportunity' =
			
			
			if(ISBLANK([DQ SP OP 30 Min Net Output Optimised]), BLANK(), [DQ SP OP 30 Min Net Output Optimised] - [DQ Net Output 30 Min Bin Last 12h])
		formatString: 0.00
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: 68ce0095-57f3-45bf-ad63-b97c782403b5

	measure 'DQ SP OP 30 Min Net MW Lost Opportunity %' = DIVIDE([DQ SP OP 30 Min Net MW Lost Opportunity],[DQ SP OP 30 Min Net Output Optimised])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: d6b00337-8511-417e-9c06-6aa64bda59b0

	measure Top5DailyDeltas = ```
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        SUMMARIZE (
			            'Date Table',
			            'Date Table'[calendar_date]
			        ),
			        "SumA", CALCULATE ( AVERAGE ( 'Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_HP_BRINE])),
			        "SumB", CALCULATE ( AVERAGE ( 'Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_calculated_hp_brine])),
			        "Delta", ABS ( CALCULATE (AVERAGE ('Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_HP_BRINE])) - 
			                       CALCULATE (AVERAGE ('Flow Calibration Alerts'[HP_VENTURI_STEAM_plus_calculated_hp_brine])))
			     )
			
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta], , DESC )) 
			
			var _top1  =  TOPN ( 1, Ranked, [Delta], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_valueA  = MAXX(_top1,[SumA])
			var _delta_perc = FORMAT( DIVIDE(MAXX(_top1,[Delta]),_delta_valueA), "Percent")
			
			RETURN
			
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( MAXX(_top1,[calendar_date]), "dd/mm/yy")
			
			```
		displayFolder: _Import\Alerts
		lineageTag: 0243b8a9-b8c4-4c7e-8555-e0086f7bfe58

	measure 'Alert Top 1 Two Phase Delta' = ```
			
			
			var _start = min('Date Table'[calendar_date])
			var _end = max('Date Table'[calendar_date])
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        CALCULATETABLE(
			        SUMMARIZE (      
			            'Date Table',
			             'Date Table'[calendar_date]
			        ),
			          'Date Table'[calendar_date] <> DATE(2024,05,12), ('Date Table'[calendar_date] >=_start  && 'Date Table'[calendar_date] <= _end)
			        ), 
			        "valueA",  [Alert HP Venturi Brine],
			        "valueB", [Alert HP Venturi Brine Calculated],
			        "Delta",  ABS ( [Alert HP Venturi Brine] - [Alert HP Venturi Brine Calculated]),
			        "Delta%",  ABS ( DIVIDE( [Alert HP Venturi Brine] - [Alert HP Venturi Brine Calculated],[Alert HP Venturi Brine]))
			           
			    )
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta%], , DESC )) 
			
			var _top1  =  TOPN ( 1, Ranked, [Delta], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_valueA  = MAXX(_top1,[valueA])
			
			var _delta_perc = FORMAT( MAXX(_top1,[Delta%]), "Percent")
			
			RETURN
			
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( _delta_date, "dd/mm/yy")
			
			
			```
		displayFolder: _Import\Alerts
		lineageTag: ea937e36-3e3e-4916-97ca-b00253f9d8af

	measure 'Alert Top 1 HP Brine Delta' = ```
			
			
			var _start = min('Date Table'[calendar_date])
			var _end = max('Date Table'[calendar_date])
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        CALCULATETABLE(
			        SUMMARIZE (
			            'Date Table',
			            'Date Table'[calendar_date]
			        ),
			              'Date Table'[calendar_date] <> DATE(2024,05,12), ('Date Table'[calendar_date] >=_start  && 'Date Table'[calendar_date] <= _end)
			        ),      
			        "valueA", [Alert HP Brine Actual],
			        "valueB", [Alert HP Brine Calculated],
			     --   "Delta", ABS ( [Alert HP Brine Actual] - [Alert HP Brine Calculated]),
			        "Delta%", ABS ( DIVIDE( [Alert HP Brine Actual] - [Alert HP Brine Calculated],[Alert HP Brine Actual]))
			     )
			
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta%], , DESC )) 
			
			var _top1  =  TOPN ( 1, Ranked, [Delta%], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_perc = FORMAT( MAXX(_top1,[Delta%]), "Percent")
			
			RETURN
			
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( _delta_date, "dd/mm/yy")
			
			```
		displayFolder: _Import\Alerts
		lineageTag: d6f477a3-b2f2-4669-afb8-40e15664cdd0

	measure 'Alert Top 1 HP Turbine Steam Delta' = ```
			
			
			var _start = min('Date Table'[calendar_date])
			var _end = max('Date Table'[calendar_date])
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        CALCULATETABLE(
			        SUMMARIZE (
			            'Date Table',
			            'Date Table'[calendar_date]
			        ),
			              'Date Table'[calendar_date] <> DATE(2024,05,12), ('Date Table'[calendar_date] >=_start  && 'Date Table'[calendar_date] <= _end)
			        ),      
			        "valueA", [Alert HP Turbine Steam Flow Actual],
			        "valueB", [Alert HP Turbine Steam Flow Calculated],
			        --"Delta", ABS ( [Alert HP Turbine Steam Flow Actual] - [Alert HP Turbine Steam Flow Calculated]),
			        "Delta%", ABS ( DIVIDE( [Alert HP Turbine Steam Flow Actual] - [Alert HP Turbine Steam Flow Calculated], [Alert HP Turbine Steam Flow Actual]))
			     )
			
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta%], , DESC )) 
			
			var _top1 = TOPN ( 1, Ranked, [Delta%], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_perc = FORMAT( MAXX(_top1,[Delta%]), "Percent")
			
			RETURN
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( _delta_date, "dd/mm/yy")
			```
		displayFolder: _Import\Alerts
		lineageTag: 93063104-a12f-492e-a87a-f3a9cdb4a7d8

	measure 'Alert Top 1 LP Turbine Steam Delta' = ```
			
			
			var _start = min('Date Table'[calendar_date])
			var _end = max('Date Table'[calendar_date])
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        CALCULATETABLE(
			        SUMMARIZE (
			            'Date Table',
			            'Date Table'[calendar_date]
			        ),
			              'Date Table'[calendar_date] <> DATE(2024,05,12), ('Date Table'[calendar_date] >=_start  && 'Date Table'[calendar_date] <= _end)
			        ),      
			        "valueA", [Alert LP Steam Flow Actual],
			        "valueB", [Alert LP Steam Flow Calculated],
			        "Delta", ABS ( [Alert LP Steam Flow Actual] - [Alert LP Steam Flow Calculated]),
			        "Delta%", ABS ( DIVIDE( [Alert LP Steam Flow Actual] - [Alert LP Steam Flow Calculated],[Alert LP Steam Flow Actual]))
			     )
			
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta%], , DESC )) 
			
			var _top1  =  TOPN ( 1, Ranked, [Delta], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_valueA  = MAXX(_top1,[valueA])
			var _delta_perc = FORMAT( MAXX(_top1,[Delta%]), "Percent")
			
			RETURN
			
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( _delta_date, "dd/mm/yy")
			
			
			```
		displayFolder: _Import\Alerts
		lineageTag: a3c31526-4b02-4846-b7e5-6a20ba86ee27

	measure 'Alert Top 1 Total Steam Flow Delta' = ```
			
			
			var _start = min('Date Table'[calendar_date])
			var _end = max('Date Table'[calendar_date])
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        CALCULATETABLE(
			        SUMMARIZE (
			            'Date Table',
			            'Date Table'[calendar_date]
			        ),
			              'Date Table'[calendar_date] <> DATE(2024,05,12), ('Date Table'[calendar_date] >=_start  && 'Date Table'[calendar_date] <= _end)
			        ),      
			        "valueA", [Alert Total Turbine Steam Flow],
			        "valueB", [Alert Total Turbine Steam Flow Calculated],
			        "Delta", ABS ( [Alert Total Turbine Steam Flow] - [Alert Total Turbine Steam Flow Calculated]),
			        "Delta%", ABS ( DIVIDE( [Alert Total Turbine Steam Flow] - [Alert Total Turbine Steam Flow Calculated], [Alert Total Turbine Steam Flow]))
			     )
			
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta%], , DESC )) 
			
			var _top1  =  TOPN ( 1, Ranked, [Delta], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_perc = FORMAT( MAXX(_top1,[Delta%]), "Percent")
			
			RETURN
			
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( _delta_date, "dd/mm/yy")
			
			
			```
		displayFolder: _Import\Alerts
		lineageTag: c11f7b26-c441-4352-920c-9a3fd9cf2c07

	measure 'Alert Top 1 GES Delta' = ```
			
			
			var _start = min('Date Table'[calendar_date])
			var _end = max('Date Table'[calendar_date])
			
			VAR DailySummary =
			    ADDCOLUMNS (
			        CALCULATETABLE(
			        SUMMARIZE (
			            'Date Table',
			            'Date Table'[calendar_date]
			        ),
			              'Date Table'[calendar_date] <> DATE(2024,05,12), ('Date Table'[calendar_date] >=_start  && 'Date Table'[calendar_date] <= _end)
			        ),      
			        "valueA", [Alert GES Actual],
			        "valueB", [Alert GES Calculated],
			        "Delta", ABS ( [Alert GES Actual] - [Alert GES Calculated]),
			         "Delta%", ABS ( DIVIDE( [Alert GES Actual] - [Alert GES Calculated],[Alert GES Actual]))
			     )
			
			VAR Ranked =
			    ADDCOLUMNS (
			        DailySummary,
			        "Rank", RANKX ( DailySummary, [Delta], , DESC )) 
			
			var _top1  =  TOPN ( 1, Ranked, [Delta], DESC )
			var _delta_date  = MAXX(_top1,[calendar_date])
			var _delta_valueA  = MAXX(_top1,[valueA])
			var _delta_perc = FORMAT( DIVIDE(MAXX(_top1,[Delta]),IF(_delta_valueA = 0,0.1,_delta_valueA)), "Percent")
			
			RETURN
			
			"Highest Delta: " & _delta_perc  & " on " & FORMAT( MAXX(_top1,[calendar_date]), "dd/mm/yy")
			
			```
		displayFolder: _Import\Alerts
		lineageTag: 41198520-995c-4a47-b45f-d181db4dbe71

	measure 'Gross MW Output Avg HH' = AVERAGE('Forecast'[GROSS_MW_OUTPUT_EFFECTIVE])
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: d0eeaaf8-ccb7-401b-b739-98455c17fdd3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross MW Output Avg Today' =
			
			var _result = CALCULATE( MAX('Date Table'[calendar_date]),'Date Table'[Actual Only] = "Actual")
			return
			CALCULATE([Gross MW Output Avg HH],'Forecast'[7_DAYS_DATE] <= _result)
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 0a09b0bd-f1cc-41f8-8b94-654270b1f597

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ SP Check Gross Variance' = ```
			
			
			var _current_row = min('DQ 30 Min Bin Last 12h'[ROW_NUM])
			var _current_gross = [DQ Gross Output 30 Min Bin Last 12h]
			
			var _next_gross = CALCULATE([DQ Gross Output 30 Min Bin Last 12h], FILTER(ALL('DQ 30 Min Bin Last 12h'), 'DQ 30 Min Bin Last 12h'[ROW_NUM] = _current_row +1))
			VAR _return = if  ( ABS( _current_gross - _next_gross) >1 && not ISBLANK(_next_gross) , "Gross output Variance > 1 MW, then no Set Point data ")
			
			RETURN
			
			_return
			
			
			
			
			```
		displayFolder: _DQ\30 Min Bin Last 12 h\Set Point
		lineageTag: 33e700b5-33fe-45fc-a5b6-a0c6d6aa1fe2

	measure 'DQ QA Check Data Delta in Minutes' = ```
			
			
			 var _LatestDate = CALCULATE( MAX( 'DQ 2 Min Bin Last 48h'[2MIN_INTERVAL_TIMESTAMP_DATE]), 'DQ 2 Min Bin Last 48h'[row_num] = 1)
			 var _LatestTime = CALCULATE( MAX( 'DQ 2 Min Bin Last 48h'[2MIN_INTERVAL_TIMESTAMP_TIME]), 'DQ 2 Min Bin Last 48h'[row_num] = 1)
			 var _LatestTimeStamp =  _LatestDate & " "& _LatestTime
			 VAR _Now = [DQ Last Refresh]
			 var _DeltainMinutes = DATEDIFF(_LatestTimeStamp, _Now,MINUTE)
			
			RETURN
			_DeltainMinutes
			```
		formatString: 0
		displayFolder: _DQ\QA
		lineageTag: 855c0aa2-0ab1-4f9c-b4cf-7d5509cafa1a

	measure 'Ambient Temp. Var. %' = DIVIDE([Ambient Temp.] - [Forecast Ambient Temp. Forecast] , [Ambient Temp.])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Temperature
		lineageTag: 97d730d1-748e-425f-9637-4dc66db9961c

	measure 'Gross MW Output Forecast HH Avg' = AVERAGE('Forecast'[Forecast_gross_output])
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: fa6a52d6-8317-419b-a039-ef33e6dced3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross  MW Output Delta %' =
			
			
			VAR _Gross_actual = [Gross MW Output Avg Today]
			RETURN
			if( ISBLANK(_Gross_actual), "", 1- DIVIDE( [Gross MW Output Avg Today],[Gross MW Output Forecast HH Avg]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast\Gross Output
		lineageTag: 1b861466-85e7-4805-b454-a66933b59643

	measure 'Forecast Humidity Actual' = AVERAGE('Forecast'[HUMIDITY_EFFECTIVE])
		displayFolder: _Import\Humidity
		lineageTag: ba0838e3-d5aa-4d94-984f-022dfeb66b2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Humidity Var. %' = DIVIDE([Forecast Humidity Actual] - [Forecast Humidity Forecast] , [Forecast Humidity Actual])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Humidity
		lineageTag: 1133ccc5-b05b-4d72-b04f-c70a0a7efcb3

	measure 'Calendar Month Year Selected' = FORMAT( MAX('Date Periods'[Date]),"mmmm/yyyy")
		displayFolder: _Import\Calendar
		lineageTag: 806fbb33-5e5b-471f-8aa4-f1b7b5145ce2

	measure 'Net MW Output Delta Avg Previous Month %' = ```
			
			/*
			 var _current_month_max = max('Date Table'[calendar_date])
			 var _current_month_min = min('Date Table'[calendar_date])
			 var _current_year_month = min('Date Table'[calendar_year_month])
			
			 var _previous_month_min = EDATE(_current_month_min,-1)
			 var _previous_month_max = EDATE(_current_month_max,-1)
			
			
			
			 VAR CurrentYearMonth = MAX('Date Table'[calendar_year_month])  -- Your YYYYMM column
			VAR CurrentYear = INT(CurrentYearMonth / 100)
			VAR CurrentMonth = MOD(CurrentYearMonth, 100)
			VAR AsDate = DATE(CurrentYear, CurrentMonth, 1)
			VAR PreviousMonthDate = EDATE(AsDate, -1)
			VAR PreviousYearMonth = YEAR(PreviousMonthDate) * 100 + MONTH(PreviousMonthDate)
			
			
			
			*/
			var _previous_month = [Previous Month YYYYMM]
			
			
			var _NetMWOutput = CALCULATE(AVERAGE('Forecast'[NET_OUTPUT_EFFECTIVE]), ALLCROSSFILTERED('Forecast'), 'Date Table'[calendar_year_month]=_previous_month)
			
			
			var _NetMWForecast = CALCULATE(AVERAGE('Forecast'[Forecast_Net_output]), ALLCROSSFILTERED('Forecast'), 'Date Table'[calendar_year_month]=_previous_month)
			
			
			
			VAR _Net_actual = _NetMWOutput
			var _netPerc = DIVIDE(  _NetMWForecast - _NetMWOutput,_NetMWOutput)
			RETURN
			_netPerc
			
			
			--RETURN 
			--_previous_month
			--CALCULATE([Net MW Output Delta Avg %],   all('Date Periods'[Date]), FILTER('Date Table', 'Date Table'[calendar_year_month] =_previous_month ))
			
			 --_current_month_min & " " & _current_month_max
			 --_previous_month_min & " " & _previous_month_max
			-- _current_year_month
			
			/*VAR _Net_actual = [Net MW Output HH Avg Today]
			RETURN
			if( ISBLANK(_Net_actual), "", 1- DIVIDE( [Net MW Output HH Avg Today],[Net MW Output Forecast HH Avg] ))*/
			```
		formatString: 0.000%;-0.000%;0.000%
		displayFolder: _Import\Forecast\Net Output
		lineageTag: d497846a-527b-438d-9aa1-8d8a96e272ec

	measure 'Previous Month YYYYMM' =
			
			VAR CurrentYearMonth = MAX('Date Table'[calendar_year_month])  -- Your YYYYMM column
			VAR CurrentYear = INT(CurrentYearMonth / 100)
			VAR CurrentMonth = MOD(CurrentYearMonth, 100)
			VAR AsDate = DATE(CurrentYear, CurrentMonth, 1)
			VAR PreviousMonthDate = EDATE(AsDate, -1)
			VAR PreviousYearMonth = YEAR(PreviousMonthDate) * 100 + MONTH(PreviousMonthDate)
			RETURN PreviousYearMonth
		formatString: 0
		displayFolder: _Import\Calendar
		lineageTag: 66abcd26-6812-42c9-8d1e-30f438c17f7a

	measure 'Net MW Output Delta Avg CF' = IF([Net MW Output Delta Avg %] <-0.02 || [Net MW Output Delta Avg %] >0.02, [Colour Red Pastel],"#4F7A8B")
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 087178a3-11c5-41ab-88f0-536aa0452f6f

	measure 'Net HH Intervals Above 2%' = ```
			
			COUNTROWS(
			    FILTER(
			        VALUES('Time Table'[Time]),
			        --[Net MW Output Delta Avg %] > 0.02 ||  [Net MW Output Delta Avg %] < -0.02
			        ABS([Net MW Output Delta Avg %])>0.05 
			))
			```
		formatString: 0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 25cc7e7b-637e-4a35-9dcd-1e14abc540d4

	measure 'Net HH Intervals Above 2% All' = ```
			
			COUNTROWS(
			    FILTER(
			        CROSSJOIN(
			            ALLSELECTED('Date Table'[calendar_date]),
			            ALLSELECTED('Time Table'[Time])
			        ),
			        CALCULATE( [Net MW Output Delta Avg %] > 0.05 || [Net MW Output Delta Avg %] < -0.05)
			    ))
			
			```
		formatString: 0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 7103ffd8-31c0-4c8a-bab3-c387dcc3dc77

	measure 'Net HH Intervals Above 2% All Previous' =
			
			VAR _PreviusMonth = [Previous Month YYYYMM]
			RETURN
			
			CALCULATE(
			    COUNTROWS(
			        FILTER(
			            CROSSJOIN(
			                'Date Table',
			                ALL('Time Table'[Time])
			            ),
			            [Net MW Output Delta Avg %] > 0.05 || [Net MW Output Delta Avg %] < -0.05
			        )
			    ),
			    ALLCROSSFILTERED('Date Table'),
			    'Date Table'[calendar_year_month] = _PreviusMonth
			)
		formatString: 0
		displayFolder: _Import\Forecast\Net Output
		lineageTag: 4e31823d-9fd2-46a5-8684-c1103bccfe7f

	measure 'Forecast GES System 80 GES %' = ```
			
			DIVIDE(
			    COUNTROWS(FILTER('Forecast', 'Forecast'[IS_GES_SYSTEM_CURRENT_EFFECTIVE] = "80_GES")),
			    COUNTROWS('Forecast')
			) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast
		lineageTag: 470a236c-3bb9-454c-b519-4e9e86ccece6

	measure 'Forecast GES System 40 60 GES %' = ```
			
			DIVIDE(
			    COUNTROWS(FILTER('Forecast', 'Forecast'[IS_GES_SYSTEM_CURRENT_EFFECTIVE] = "40_60_GES")),
			    COUNTROWS('Forecast')
			) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast
		lineageTag: 85ca0a25-732f-4d41-be0a-20e62b5230c9

	measure 'Forecast GES System 40 60 80 GES %' = ```
			
			DIVIDE(
			    COUNTROWS(FILTER('Forecast', 'Forecast'[IS_GES_SYSTEM_CURRENT_EFFECTIVE] = "40_60_80_GES")),
			    COUNTROWS('Forecast')
			) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast
		lineageTag: e6bf0be3-41c8-40e0-b75a-8c67ffe26eee

	measure 'DQ QA Set Optimiser Last Process Delta Flag' = ```
			
			var _delta_in_minutes = IF(ISBLANK( MAX('DQ Set Point Optimiser Process Check'[delta_in_min])),0,MAX('DQ Set Point Optimiser Process Check'[delta_in_min]))
			
			RETURN
			IF(_delta_in_minutes >=120,"Set Point Model Stalled", "Set Point Model OK")
			
			```
		displayFolder: _DQ\QA
		lineageTag: c3fa9f01-bb33-4f64-a6fb-b3f5adcb4a25

	measure 'DQ QA Set Optimiser Last Process' = MAX('DQ Set Point Optimiser Process Check'[ts_date_time])
		displayFolder: _DQ\QA
		lineageTag: 7f465c1a-1dfd-4077-9a2e-2f18c6fde9ab

	measure 'BRIP 1st 2nd %' = ```
			DIVIDE(
			                         SUMX(Forecast,IF( 'Forecast'[IS_BRIPSYSTEM_1ST_2ND_STAGE_EFFECTIVE] = 1,1,0)),
			                         COUNTROWS('Forecast')
			                    )
			
			```
		formatString: 0%;-0%;0%
		displayFolder: _Import\Forecast
		lineageTag: 8ab49bfa-03b9-4a80-9d48-e2742486b5cb

	measure 'BRIP 1st %' = ```
			DIVIDE(
			                         SUMX(Forecast,IF( 'Forecast'[IS_BRIPSYSTEM_1ST_STAGE_ONLY_EFFECTIVE] = 1,1,0)),
			                         COUNTROWS('Forecast')
			                    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast
		lineageTag: 6d8c72cc-ac6a-4570-955f-472f2a30a78b

	measure 'BRIP Off Line %' =
			DIVIDE(
			                         SUMX(Forecast,IF( 'Forecast'[IS_BRIPSYSTEM_REINJECTION_OFFLINE_EFFECTIVE] = 1,1,0)),
			                         COUNTROWS('Forecast')
			                    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Import\Forecast
		lineageTag: 7608449a-14d4-4b8e-91f0-2275f2b53089

	partition _Measures_Folder = m
		mode: import
		queryGroup: Support
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

