table 'Date Table'
	lineageTag: e9c6d80c-bf18-4983-97d2-f83baf9d9953
	dataCategory: Time

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 281dd821-355b-4133-934b-db08915505b5
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = User

	column calendar_date
		dataType: dateTime
		isKey
		formatString: d/mm/yy
		lineageTag: 0376f77f-a0c8-41b8-9e0c-cbe5a31c00fa
		summarizeBy: none
		sourceColumn: calendar_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column financial_year
		dataType: int64
		formatString: 0
		lineageTag: e613e758-d73f-4004-a3d1-339ce5a8b24a
		summarizeBy: sum
		sourceColumn: financial_year

		annotation SummarizationSetBy = Automatic

	column financial_month_number
		dataType: int64
		formatString: 0
		lineageTag: d39f7239-4834-4f77-ba34-df97548435d3
		summarizeBy: none
		sourceColumn: financial_month_number

		annotation SummarizationSetBy = User

	column financial_quarter_number
		dataType: int64
		formatString: 0
		lineageTag: 01a50a9d-f7b6-43c2-9b23-3b5b1733347a
		summarizeBy: none
		sourceColumn: financial_quarter_number

		annotation SummarizationSetBy = User

	column tax_year
		dataType: int64
		formatString: 0
		lineageTag: 791c526c-076e-4f0d-8f6f-8785c2681aa0
		summarizeBy: none
		sourceColumn: tax_year

		annotation SummarizationSetBy = User

	column tax_quarter_number
		dataType: int64
		formatString: 0
		lineageTag: 59154c25-d55d-4c91-987a-68dab3ece1f1
		summarizeBy: none
		sourceColumn: tax_quarter_number

		annotation SummarizationSetBy = User

	column 'Actual Only' = if ('Date Table'[calendar_date] <DATEVALUE( [Last Refresh]) ,"Actual","Forecast")
		lineageTag: f88c74b1-f649-439a-b560-23be8a1a74fc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Week Number' = WEEKNUM('Date Table'[calendar_date], 21)
		formatString: 0
		lineageTag: d1006a96-e457-45cd-a38a-af18d05e548f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Actual Only incluing Today' = if ('Date Table'[calendar_date] <=DATEVALUE( [Last Refresh]) ,"Actual","Forecast")
		lineageTag: cdbd9599-6ae2-42b0-a07c-715577146646
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column financial_month_name
		dataType: string
		lineageTag: 62907f3c-f4a2-484e-867b-b66bc96df4a6
		summarizeBy: none
		sourceColumn: financial_month_name

		annotation SummarizationSetBy = Automatic

	column financial_quarter_name
		dataType: string
		lineageTag: 6ab8d09b-ab1a-4be1-81a0-887f7f7b401d
		summarizeBy: none
		sourceColumn: financial_quarter_name

		annotation SummarizationSetBy = Automatic

	column calendar_weekday_full_name
		dataType: string
		lineageTag: 8cc33507-d205-4ee9-b217-a7e4c668ed74
		summarizeBy: none
		sourceColumn: calendar_weekday_full_name

		annotation SummarizationSetBy = Automatic

	column tax_month_number
		dataType: string
		lineageTag: 765be01e-3304-4169-aefc-b72e7062d868
		summarizeBy: none
		sourceColumn: tax_month_number

		annotation SummarizationSetBy = Automatic

	column tax_quarter_name
		dataType: string
		lineageTag: de015093-2c57-4de1-aa15-de58b4ff381b
		summarizeBy: none
		sourceColumn: tax_quarter_name

		annotation SummarizationSetBy = Automatic

	column calendar_year_month
		dataType: int64
		formatString: 0
		lineageTag: e438b730-b75e-4757-807d-f0635871d1f5
		summarizeBy: none
		sourceColumn: calendar_year_month

		annotation SummarizationSetBy = User

	partition 'Date Table' = m
		mode: import
		queryGroup: Calendar
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(DB_HOST,DB_PATH, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    dev_generation_Database = Source{[Name="dev_generation",Kind="Database"]}[Data],
				    geothermal_Schema = dev_generation_Database{[Name="geothermal",Kind="Schema"]}[Data],
				    reporting_calendar_v_View = geothermal_Schema{[Name="reporting_calendar_v",Kind="View"]}[Data],
				    #"Filtered Rows1" = Table.SelectRows(reporting_calendar_v_View, each [calendar_date] >= #"Flow Alerts First Date Var" and [calendar_date] <= #"Forecast Last Date")
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

