table 'Flow Calibration Alerts'
	lineageTag: 191bd445-7d9c-44b4-8297-3dfaf55813ae

	column ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 34b935a1-3a20-42e6-9b02-92e0e7e815f5
		summarizeBy: none
		sourceColumn: ts

		annotation SummarizationSetBy = Automatic

	column ts_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35d3fedb-6d2a-454a-950c-a578b314b871
		summarizeBy: none
		sourceColumn: ts_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ts_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: ba479e04-813d-49cb-ac04-3e4b92bfce45
		summarizeBy: none
		sourceColumn: ts_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HP_turbine_steam_flow_calculated
		dataType: double
		lineageTag: dccdf313-3847-4ec9-8f38-2162a5759f75
		summarizeBy: sum
		sourceColumn: HP_turbine_steam_flow_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GES_calculated
		dataType: double
		lineageTag: dc83ac34-c583-4664-824d-05e88804ba9a
		summarizeBy: sum
		sourceColumn: GES_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_turbine_steam_flow_calculated
		dataType: double
		lineageTag: 4afaedb4-ac33-4094-9947-6a8c24cbcb0f
		summarizeBy: sum
		sourceColumn: Total_turbine_steam_flow_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LP_turbine_steam_flow_calculated
		dataType: double
		lineageTag: 21dc791b-f175-4991-9c25-f21ea81ce07b
		summarizeBy: sum
		sourceColumn: LP_turbine_steam_flow_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_brine_flow_calculated
		dataType: double
		lineageTag: 46dc6f18-eb64-479f-b17f-1d4bb3c27bbe
		summarizeBy: sum
		sourceColumn: HP_brine_flow_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_GES_STEAM_SUPPLY
		dataType: double
		lineageTag: b1ef7bcb-5cb6-40ef-b384-139a748e514b
		summarizeBy: sum
		sourceColumn: HP_GES_STEAM_SUPPLY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_TURBINE_STEAM_FLOW
		dataType: double
		lineageTag: f72b0211-7781-4518-abe3-0140ab25379b
		summarizeBy: sum
		sourceColumn: TOTAL_TURBINE_STEAM_FLOW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_TURBINE_STEAM_FLOW
		dataType: double
		lineageTag: 0bcc0427-40a4-4b34-8a36-7042017a86ae
		summarizeBy: sum
		sourceColumn: HP_TURBINE_STEAM_FLOW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_BRINE_FLOW
		dataType: double
		lineageTag: 394dd9b8-31e3-4889-8ab6-02e418c44927
		summarizeBy: sum
		sourceColumn: HP_BRINE_FLOW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LP_STEAM_FLOW
		dataType: double
		lineageTag: 33b8e618-3182-4f1d-97fd-4fa7e0883c63
		summarizeBy: sum
		sourceColumn: LP_STEAM_FLOW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GES_constant
		dataType: double
		lineageTag: 9e4c0148-5e34-4298-bfaa-fe8e1070d55b
		summarizeBy: sum
		sourceColumn: GES_constant

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_VENTURI_STEAM_plus_HP_BRINE
		dataType: double
		lineageTag: 58eb7bb0-7330-4cba-a9a4-dd0b22ae713e
		summarizeBy: sum
		sourceColumn: HP_VENTURI_STEAM_plus_HP_BRINE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_VENTURI_STEAM_plus_calculated_hp_brine
		dataType: double
		lineageTag: ca34e012-add6-4a64-a0c8-73e76aac4968
		summarizeBy: sum
		sourceColumn: HP_VENTURI_STEAM_plus_calculated_hp_brine

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sum_of_wells
		dataType: double
		lineageTag: 326db165-3e14-4d44-b627-f5f49054ebfe
		summarizeBy: sum
		sourceColumn: Sum_of_wells

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_VENTURI_STEAM_plus_LP_BRINE_plus_LP_STEAM
		dataType: double
		lineageTag: 24934ace-1601-44ea-b683-a58b920f589d
		summarizeBy: sum
		sourceColumn: HP_VENTURI_STEAM_plus_LP_BRINE_plus_LP_STEAM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_TURBINE_FLOW_plus_GES_plus_LP_BRINE
		dataType: double
		lineageTag: c0076b7e-6f75-478b-b4b3-46256d82effe
		summarizeBy: sum
		sourceColumn: TOTAL_TURBINE_FLOW_plus_GES_plus_LP_BRINE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Flow Calibration Alerts' = m
		mode: import
		queryGroup: Forecast
		source = ```
				let
				    Source = Value.NativeQuery(DatabricksMultiCloud.Catalogs(DB_HOST, DB_PATH, [Catalog="dev_generation", Database=null, EnableAutomaticProxyDiscovery=null]){[Name="dev_generation",Kind="Database"]}[Data], "SELECT * FROM dev_generation.geothermal.reporting_geo_flow_calibration_alerts_v 
				    LIMIT " & DB_LIMITS_ROWS
				    
				    , null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ts_time", type time}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

