table 'GES Hindcast Model'
	lineageTag: 495279e1-14b8-4194-8d9c-d756e8e1f7a6

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20a58fed-dc09-433c-a188-647f4cf07446
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0947123f-61e1-40ff-90e3-be5f31eebc76
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column model_update_latest
		dataType: dateTime
		formatString: General Date
		lineageTag: c7ba325b-0897-469e-9cfd-3d9ca39f05b8
		summarizeBy: none
		sourceColumn: model_update_latest

		annotation SummarizationSetBy = Automatic

	column NET_OUTPUT_ACTUAL
		dataType: double
		lineageTag: 707eb546-61d1-4045-addc-4a62c98a2d4e
		summarizeBy: sum
		sourceColumn: NET_OUTPUT_ACTUAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_baseline
		dataType: double
		lineageTag: 9888ab9a-caf3-4c63-80ea-29ee6445f644
		summarizeBy: sum
		sourceColumn: Net_output_baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GES_capacity_baseline
		dataType: int64
		formatString: 0
		lineageTag: 3e020a24-1b35-476a-b449-7de9749c8e9e
		summarizeBy: sum
		sourceColumn: GES_capacity_baseline

		annotation SummarizationSetBy = Automatic

	column PARASITIC_LOAD_ACTUAL
		dataType: double
		lineageTag: 069260a0-96a3-45c3-9bac-70a55804bbe9
		summarizeBy: sum
		sourceColumn: PARASITIC_LOAD_ACTUAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Parasitic_load_calculated
		dataType: double
		lineageTag: 82f7f506-1504-4a80-8a7e-f7488260afe4
		summarizeBy: sum
		sourceColumn: Parasitic_load_calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_80
		dataType: double
		lineageTag: 6c77d600-35b0-4154-b880-26ae1c933ed9
		summarizeBy: sum
		sourceColumn: Net_output_80

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Parastic_load_80
		dataType: double
		lineageTag: 3e702223-c24e-4161-98cd-91a8bfebb763
		summarizeBy: sum
		sourceColumn: Parastic_load_80

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_40_60
		dataType: double
		lineageTag: 291df783-05d0-4c46-9a7e-cc797c819f23
		summarizeBy: sum
		sourceColumn: Net_output_40_60

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Parastic_load_40_60
		dataType: double
		lineageTag: 0fa0d104-12e3-4743-a078-69ce4b91168d
		summarizeBy: sum
		sourceColumn: Parastic_load_40_60

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'GES Hindcast Model' = m
		mode: import
		queryGroup: Forecast
		source = ```
				let
				    Source = Value.NativeQuery(DatabricksMultiCloud.Catalogs(DB_HOST, DB_PATH, [Catalog="dev_generation", Database=null, EnableAutomaticProxyDiscovery=null]){[Name="dev_generation",Kind="Database"]}[Data], "SELECT * FROM dev_generation.geothermal.reporting_geo_ges_hindcast_model_daily_v 
				    LIMIT " & DB_LIMITS_ROWS
				    
				    , null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Time", type time}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

