table 'Hindcast Model'
	lineageTag: 83e810d6-0be7-43b5-8931-af2eb36d9fb3

	column TS_DATE
		dataType: dateTime
		formatString: d/mm/yy
		lineageTag: 881a21d4-30c8-466c-a213-5501538ea39e
		summarizeBy: none
		sourceColumn: TS_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TS_TIME
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6ee6d9f7-036a-452d-8d72-7d4a63fc3924
		summarizeBy: none
		sourceColumn: TS_TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column NET_OUTPUT_ACTUAL
		dataType: double
		lineageTag: 44f04f2b-dfdb-4657-abd5-10a2394e0e75
		summarizeBy: sum
		sourceColumn: NET_OUTPUT_ACTUAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NTGA_STEAM_Baseline
		dataType: double
		lineageTag: 151c97fc-0f6d-4974-9caf-d1fb41fdd62d
		summarizeBy: sum
		sourceColumn: NTGA_STEAM_Baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_baseline
		dataType: double
		lineageTag: 0b800e5a-5a8f-4127-8cf8-ac125363112a
		summarizeBy: sum
		sourceColumn: Net_output_baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_0_NTGA
		dataType: double
		lineageTag: 634ce724-c6d8-4c6b-8e1a-45073e8fd5e0
		summarizeBy: sum
		sourceColumn: Net_output_0_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_5_NTGA
		dataType: double
		lineageTag: f2d47cc1-fa35-4f36-ad81-44318bc773ef
		summarizeBy: sum
		sourceColumn: Net_output_5_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_10_NTGA
		dataType: double
		lineageTag: 4e320f67-5d0d-4e5c-90e0-1b3ae4973135
		summarizeBy: sum
		sourceColumn: Net_output_10_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_15_NTGA
		dataType: double
		lineageTag: 9acda69b-c3be-4460-bb7a-42d7ef8b4e5e
		summarizeBy: sum
		sourceColumn: Net_output_15_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_20_NTGA
		dataType: double
		lineageTag: e18028b0-a51e-41b4-bb9f-c3f78aeb8ed4
		summarizeBy: sum
		sourceColumn: Net_output_20_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_25_NTGA
		dataType: double
		lineageTag: e7c8a6f8-af23-47c8-9dce-c1a6647d2259
		summarizeBy: sum
		sourceColumn: Net_output_25_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_30_NTGA
		dataType: double
		lineageTag: afd6cbef-1363-42fe-bf52-6859f088f4b4
		summarizeBy: sum
		sourceColumn: Net_output_30_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Net_output_35_NTGA
		dataType: double
		lineageTag: a5e7323f-f6f7-4b12-a633-77c268030c75
		summarizeBy: sum
		sourceColumn: Net_output_35_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column model_update_latest
		dataType: dateTime
		formatString: General Date
		lineageTag: fa0e4eb3-60a8-42f2-a9ef-c6d29d654622
		summarizeBy: none
		sourceColumn: model_update_latest

		annotation SummarizationSetBy = Automatic

	column Actual_Forecast
		dataType: string
		lineageTag: bb1237fa-ff51-4e60-8caf-ee7176311604
		summarizeBy: none
		sourceColumn: Actual_Forecast

		annotation SummarizationSetBy = Automatic

	column Enthalpy_0_NTGA
		dataType: double
		lineageTag: c9f733da-54f7-4ba1-9b90-9764717ea5ce
		summarizeBy: sum
		sourceColumn: Enthalpy_0_NTGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Hindcast Model' = m
		mode: import
		queryGroup: Forecast
		source = ```
				let
				    Source = Value.NativeQuery(DatabricksMultiCloud.Catalogs(DB_HOST, DB_PATH, [Catalog="dev_generation", Database=null, EnableAutomaticProxyDiscovery=null]){[Name="dev_generation",Kind="Database"]}[Data], "SELECT * FROM dev_generation.geothermal.reporting_geo_hindcast_model_daily_latest_v 
				    LIMIT " & DB_LIMITS_ROWS
				    
				    , null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"TS_TIME", type time}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

