table 'PI TAGs'
	lineageTag: 8158692f-90b8-4f1d-a981-2ed72a298b49

	column 'PI TAG'
		dataType: string
		lineageTag: 87f5ed05-eac4-401d-90f3-d208deda5e58
		summarizeBy: none
		sourceColumn: PI TAG

		annotation SummarizationSetBy = Automatic

	column 'Dashboard Name'
		dataType: string
		lineageTag: a42b1457-7be2-43cd-9fcd-651e865bc3f9
		summarizeBy: none
		sourceColumn: Dashboard Name

		annotation SummarizationSetBy = Automatic

	column 'Slugging Limit Fletcher'
		dataType: string
		lineageTag: 4e4e41a9-64bf-4e34-b0ef-9ea7776bd76c
		summarizeBy: none
		sourceColumn: Slugging Limit Fletcher

		annotation SummarizationSetBy = Automatic

	column 'Slugging Limit CHH'
		dataType: string
		lineageTag: 2e5a0eea-4353-44ad-8aa6-d154d07915f3
		summarizeBy: none
		sourceColumn: Slugging Limit CHH

		annotation SummarizationSetBy = Automatic

	column 'Slugging Limit Putuaki'
		dataType: string
		lineageTag: 9d8f760a-311c-4c8a-b63e-06384cb3ed6b
		summarizeBy: none
		sourceColumn: Slugging Limit Putuaki

		annotation SummarizationSetBy = Automatic

	column 'Streaming Table Field'
		dataType: string
		lineageTag: fe856cd6-f42f-4803-b321-6bad1fdb9f93
		summarizeBy: none
		sourceColumn: Streaming Table Field

		annotation SummarizationSetBy = Automatic

	column 'Databricks Field'
		dataType: string
		lineageTag: cfb5a43e-1bbf-4b7b-bb85-45c547e308bb
		summarizeBy: none
		sourceColumn: Databricks Field

		annotation SummarizationSetBy = Automatic

	partition 'PI TAGs' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lZnbcqM4EIZfhZqrmdpxFnDsZC/FwUDCaUGOZ2oypSI2ZbNjgwvjSeVt9ln2yVbiZIFBmFRubND/tRqp/0b+8eOT4EMkeYaLALIc6HjId1VV+fS1/8IzWE10YE8F2Z/xwp0CZHDnvuALl/+fXylhqU+4faESFtnCYrxBfhZsQySl0RGHJ5/TNIwzfF20lSpmeel5qg0vsjNBVvnbZaUuWalDVmTLguyQnI67MI3WCIaHY5gG2TkNkZJ+4FuAJRlYDkHVcvHHV/ynA2viGq+vRN+HGi/IsKkPDm8Rjouj1JpIHH8cosU+eUcwQV4Yxf+E6yxKYnwDnoatooXprBB0kKca9pMqQ8OxLzOa8/ICE69m0iuL3DQ8nYowevWR66m+v/TUBsjtAslJvAnjU5giPcnew/0eNacqO7ai2r7qId2BK9U08/SpHoAXeVMGAt/OXB+mih+Bizpel1XE+dftR2MBTSjiHwOQugESCyCOAcjdAJkFmI4BKN0AhQW47wc4jmnYGl4rK/w4F8Bu7Fz2VYJwgcIP7OtrEYmJaO9xghjY49ciMhMhdyCmYxEKE6F0IO7HIlQmQu1AzMYiFkzEogMxH4vQmAitA/EwFqEzEXoH4nEswmAijA7EX2MRT0zE0zUC7242Ikn2UbzFdvGOS4gR78MMlSUlyMKrqk4TDdtUISKFpvLGsqpPB6t6wVxhQpq7VamNVgCSqWBruqg9FF7Xq6aFMYkwSVGlC6K04eNyst8geE7fiDn60YZMRVNt4ka4PlaTAoaXzwN/YeIZLT2pjMF6LnxKZMSQJqcTukTinLPjmbQlmuf4PrJWyFlCdwm7KjBRt+TCZHMdrhjNWasmRHfRxbrxl+3PbWVdX4p1n6C7XN4ccGW6Gwk8ISvJot84OVkYHKongvU11Uc+VIGF/KXrmt87KKZEHIT5hPQj8sNjmZrapYqoSnmq87gGANwXdnYhRLiOmHQ85UOmlfM+B5hmj/KUSlCu1ZEge71FSnRa74J0G1LZKQC2rJFNAIttd22wT/Oh9JwP0SbKSK+pLy1DMeD3cuUVvaXVHEzdTok8B/cCzm2yQSvSjYnI3QWnOthnQK56joLyXgxf1YGvNjaaBASRxEl3Gv7+vN3iHcWZ0SHKCto3iigyieIwcTqWOGMSZ8NEYZD4rYWcM5HzYSQ/Fjlj5nU2nFfsK+OQYE4vHvietKFzevnAldONfbzlcebgYqLYcoIz3rdZsEdWAcLGApbYYCAwkVVp44+T/IMdZn3V8Xm7zyvAEXnZGashfC8ZrpnkLQe6yINLUohttXJHeQFKd5xA92pXmr1Fy7ytaD3Wr05mVVqol7AWqaeKmXQVu7W6mP2VrEbVE/Kx37tJlL9DX00M+djgXccoGoruTDYBVhDFqOnvzRbCAoZdW25h983m4eGqeSjluFyu/5XazmeClxRZJ3nceC2Vuq5rTPLPk66g7Wwb0I9ACQ9BvCEyUAO0jSiqBezqGMR3xcnCgJMpXj++e1dfI4M4GPxqhecGaXCKsmiNzCQg4i7wgG9AQ0amA7rezS5B17eSYZUOV+rQjF88o1q5z/wN1ep+1B7GxAcm8WGYOBtF9LMgP9BQ42wX7I/EBn0I8uML7MA6MN3v1EOnvioHctRAKnV+tm2tW/98PO4/6IMTbMetpVt0Re1zE1eTxIFzh6LmFcc19DFNmbii/hXdHX1AQ2WuOgUS+B7xuuGle7pCmDS3RLpRW4p6UtoVKVu5DFVKuNc4wfuvkOXaV1shlHDcocm74PBGHU8Q5ZKPeygZr3hJ9dopLAJhp7BEmEyEOYzoP7x5CdbnMy6W58MR3fPUaeMLkOUlrpNL/LpALjTeunBRng4cFdDC8z7heYfw/Qjhxz7hxw7h2YBw42WD+4Njt97NWztaca7/ZQWPYDbqxcITubzScFG8vuNIyW0Z3ZWViZ0GJ17q0KPIXm+kv+RIlduFwea/f1tmfukvyYrqHkzq5Dnf57lOVYl2Hy2Jxd9dLzuk2Rzm8738+a18vpcvDPPFXr5wK1/s5YvD/GkvX7yVP+3mEzMb5s+6+fngG/mzvvnPcQqxmS5zL+CIpeoqUDiqrn2ie/GeRMyLB9EI4aM1ticCzeQE4dcLVx90cC/JnvwecxkOyHGGpjM3Ui7DYx2YBvHpEJ1OJCW9UgLjbLo+qaI8qGwk+34jocZ44aS2Xu6Iayb3GXzhrITMbBXFG9KDZJd+k/u8/FIjeFOWZlc//IxB/fk2iiUyWD//Bw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Streaming Table Field" = _t, #"Databricks Field" = _t, #"PI TAG" = _t, #"Dashboard Name" = _t, #"Slugging Limit Fletcher" = _t, #"Slugging Limit CHH" = _t, #"Slugging Limit Putuaki" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Databricks Field", type text}, {"PI TAG", type text}, {"Dashboard Name", type text}, {"Slugging Limit Fletcher", type text}, {"Slugging Limit CHH", type text}, {"Slugging Limit Putuaki", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

